project_id = "nrcdtxgmlhxbtfppxqop"

[api]
enabled = true
port = 54321

[db]
port = 54322

[studio]
enabled = true
port = 54323

[inbucket]
enabled = true
port = 54324

[storage]
enabled = true
file_size_limit = "50MiB"

[auth]
enabled = true
site_url = "http://localhost:3000"

[functions.mesomb-payment]
verify_jwt = true

[functions.check-payment-status]
verify_jwt = true

[functions.send-test-notification]
verify_jwt = false

[functions.send-notification-email]
verify_jwt = false

[functions.mesomb-webhook]
verify_jwt = false

[functions.admin-resolve-transaction]
verify_jwt = true

[functions.help-chat]
verify_jwt = false

[functions.ai-grade]
verify_jwt = false

[functions.school-create-student]
verify_jwt = true

[functions.payout-security]
verify_jwt = true

