import React, { createContext, useContext, useState, useEffect } from 'react';

interface LanguageContextType {
  language: 'fr' | 'en';
  setLanguage: (lang: 'fr' | 'en') => void;
  t: (key: string) => string;
}

const translations = {
  fr: {
    navigation: 'Navigation',
    homepage: 'Page d\'accueil',
    features: 'Fonctionnalités',
    pricing: 'Tarification',
    contact: 'Contact',
    login: 'Se connecter',
    logout: 'Déconnexion',
    register: 'S\'inscrire',
    dashboard: 'Tableau de bord',
    profile: 'Profil',
    settings: 'Paramètres',
    welcome: 'Bienvenue',
    description: 'Description',
    get_started: 'Commencer',
    about_us: 'À propos de nous',
    our_team: 'Notre équipe',
    services: 'Services',
    testimonials: 'Témoignages',
    faq: 'FAQ',
    blog: 'Blog',
    news: 'Actualités',
    careers: 'Carrières',
    terms: 'Conditions d\'utilisation',
    privacy: 'Politique de confidentialité',
    cookie: 'Politique de cookies',
    support: 'Support',
    help: 'Aide',
    documentation: 'Documentation',
    api: 'API',
    community: 'Communauté',
    forum: 'Forum',
    chat: 'Chat',
    email: 'Courriel',
    phone: 'Téléphone',
    address: 'Adresse',
    copyright: 'Droits d\'auteur',
    all_rights_reserved: 'Tous droits réservés',
    home: 'Accueil',
    more: 'Plus',
    exams: 'Épreuves',
    practice: 'Pratique',
    quizzes: 'Quiz',
    lessons: 'Leçons',
    courses: 'Cours',
    curriculum: 'Programme',
    teachers: 'Professeurs',
    students: 'Étudiants',
    grades: 'Notes',
    calendar: 'Calendrier',
    messages: 'Messages',
    notifications: 'Notifications',
    tasks: 'Tâches',
    files: 'Fichiers',
    resources: 'Ressources',
    tools: 'Outils',
    reports: 'Rapports',
    analytics: 'Analytique',
    performance: 'Performance',
    progress: 'Progrès',
    results: 'Résultats',
    feedback: 'Commentaires',
    survey: 'Sondage',
    poll: 'Vote',
    events: 'Événements',
    webinars: 'Webinaires',
    workshops: 'Ateliers',
    seminars: 'Séminaires',
    conferences: 'Conférences',
    activities: 'Activités',
    achievements: 'Réalisations',
    awards: 'Prix',
    certificates: 'Certificats',
    partners: 'Partenaires',
    sponsors: 'Commanditaires',
    investors: 'Investisseurs',
    clients: 'Clients',
    projects: 'Projets',
    products: 'Produits',
    solutions: 'Solutions',
    services_offered: 'Services offerts',
    case_studies: 'Études de cas',
    success_stories: 'Histoires de succès',
    mission: 'Mission',
    vision: 'Vision',
    values: 'Valeurs',
    team: 'Équipe',
    leadership: 'Direction',
    board_of_directors: 'Conseil d\'administration',
    advisors: 'Conseillers',
    careers_at: 'Carrières chez',
    open_positions: 'Postes ouverts',
    apply_now: 'Postuler maintenant',
    internships: 'Stages',
    volunteering: 'Bénévolat',
    diversity: 'Diversité',
    inclusion: 'Inclusion',
    equity: 'Équité',
    accessibility: 'Accessibilité',
    sustainability: 'Durabilité',
    impact: 'Impact',
    donate: 'Faire un don',
    volunteer: 'Bénévole',
    join_us: 'Rejoignez-nous',
    subscribe: 'S\'abonner',
    follow_us: 'Suivez-nous',
    share: 'Partager',
    like: 'J\'aime',
    comment: 'Commenter',
    read_more: 'Lire la suite',
    view_all: 'Voir tout',
    latest_news: 'Dernières nouvelles',
    featured_articles: 'Articles en vedette',
    popular_topics: 'Sujets populaires',
    categories: 'Catégories',
    tags: 'Mots-clés',
    archive: 'Archive',
    search: 'Rechercher',
    no_results_found: 'Aucun résultat trouvé',
    error_404: 'Erreur 404',
    page_not_found: 'Page non trouvée',
    back_to_home: 'Retour à l\'accueil',
    loading: 'Chargement',
    please_wait: 'Veuillez patienter',
    submit: 'Soumettre',
    send: 'Envoyer',
    reset: 'Réinitialiser',
    update: 'Mettre à jour',
    delete: 'Supprimer',
    cancel: 'Annuler',
    save: 'Enregistrer',
    edit: 'Modifier',
    add_new: 'Ajouter',
    create: 'Créer',
    manage: 'Gérer',
    view: 'Voir',
    details: 'Détails',
    options: 'Options',
    actions: 'Actions',
    confirm: 'Confirmer',
    are_you_sure: 'Êtes-vous sûr ?',
    yes: 'Oui',
    no: 'Non',
    success: 'Succès',
    error: 'Erreur',
    warning: 'Avertissement',
    information: 'Information',
    required_fields: 'Champs obligatoires',
    invalid_email: 'Adresse e-mail invalide',
    password_mismatch: 'Les mots de passe ne correspondent pas',
    password_length: 'Le mot de passe doit contenir au moins 8 caractères',
    username_exists: 'Ce nom d\'utilisateur existe déjà',
    email_exists: 'Cette adresse e-mail existe déjà',
    login_failed: 'Échec de la connexion',
    registration_successful: 'Inscription réussie',
    password_reset_sent: 'Un e-mail de réinitialisation du mot de passe a été envoyé',
    password_reset_successful: 'Réinitialisation du mot de passe réussie',
    profile_updated: 'Profil mis à jour',
    data_saved: 'Données enregistrées',
    data_deleted: 'Données supprimées',
    item_added: 'Élément ajouté',
    item_updated: 'Élément mis à jour',
    item_deleted: 'Élément supprimé',
    message_sent: 'Message envoyé',
    subscription_successful: 'Abonnement réussi',
    payment_successful: 'Paiement réussi',
    order_placed: 'Commande passée',
    download_started: 'Téléchargement démarré',
    file_uploaded: 'Fichier téléchargé',
    task_completed: 'Tâche terminée',
    event_created: 'Événement créé',
    award_received: 'Prix reçu',
    certificate_earned: 'Certificat obtenu',
    thank_you: 'Merci',
    congratulations: 'Félicitations',
    welcome_aboard: 'Bienvenue à bord',
    get_in_touch: 'Contactez-nous',
    send_us_a_message: 'Envoyez-nous un message',
    your_name: 'Votre nom',
    your_email: 'Votre e-mail',
    subject: 'Sujet',
    message: 'Message',
    i_agree_to_the: 'J\'accepte les',
    and: 'et',
    privacy_policy: 'politique de confidentialité',
    terms_of_service: 'conditions d\'utilisation',
    sign_up_for_our_newsletter: 'Inscrivez-vous à notre newsletter',
    enter_your_email: 'Entrez votre e-mail',
    subscribe_now: 'Abonnez-vous maintenant',
    stay_up_to_date: 'Restez à jour',
    never_miss_an_update: 'Ne manquez jamais une mise à jour',
    we_respect_your_privacy: 'Nous respectons votre vie privée',
    unsubscribe_at_any_time: 'Désabonnez-vous à tout moment',
    learn_more: 'En savoir plus',
    explore: 'Explorer',
    discover: 'Découvrir',
    browse: 'Épreuves',
    find_out_more: 'Découvrez-en plus',
    start_learning: 'Commencer à apprendre',
    improve_your_skills: 'Améliorez vos compétences',
    become_an_expert: 'Devenez un expert',
    unlock_your_potential: 'Libérez votre potentiel',
    achieve_your_goals: 'Atteignez vos objectifs',
    transform_your_life: 'Transformez votre vie',
    invest_in_yourself: 'Investissez en vous-même',
    join_our_community: 'Rejoignez notre communauté',
    connect_with_experts: 'Connectez-vous avec des experts',
    share_your_knowledge: 'Partagez vos connaissances',
    get_inspired: 'Inspirez-vous',
    stay_motivated: 'Restez motivé',
    celebrate_success: 'Célébrez le succès',
    make_a_difference: 'Faites la différence',
    create_a_better_future: 'Créez un avenir meilleur',
    together_we_can: 'Ensemble, nous pouvons',
    making_education_accessible: 'Rendre l\'éducation accessible',
    empowering_learners_worldwide: 'Autonomiser les apprenants du monde entier',
    building_a_brighter_tomorrow: 'Construire un avenir meilleur',
    education_for_all: 'L\'éducation pour tous',
    a_world_of_knowledge: 'Un monde de connaissances',
    your_path_to_success: 'Votre chemin vers le succès',
    the_future_of_learning: 'L\'avenir de l\'apprentissage',
    unlocking_human_potential: 'Libérer le potentiel humain',
    transforming_lives_through_education: 'Transformer des vies grâce à l\'éducation',
    creating_opportunities_for_everyone: 'Créer des opportunités pour tous',
    investing_in_the_next_generation: 'Investir dans la prochaine génération',
    inspiring_a_love_of_learning: 'Inspirer l\'amour de l\'apprentissage',
    making_a_positive_impact: 'Avoir un impact positif',
    building_a_global_community: 'Construire une communauté mondiale',
    connecting_people_through_education: 'Connecter les gens grâce à l\'éducation',
    empowering_individuals_and_communities: 'Autonomiser les individus et les communautés',
    creating_a_more_equitable_world: 'Créer un monde plus équitable',
    working_together_for_a_better_future: 'Travailler ensemble pour un avenir meilleur',
    join_us_on_this_journey: 'Rejoignez-nous dans ce voyage',
    together_we_can_make_a_difference: 'Ensemble, nous pouvons faire la différence',
    thank_you_for_being_part_of_our_community: 'Merci de faire partie de notre communauté',
    we_appreciate_your_support: 'Nous apprécions votre soutien',
    together_we_are_making_a_difference: 'Ensemble, nous faisons la différence',
    welcome_to_our_platform: 'Bienvenue sur notre plateforme',
    we_are_excited_to_have_you_with_us: 'Nous sommes ravis de vous avoir parmi nous',
    let_s_start_learning_together: 'Commençons à apprendre ensemble',
    we_are_here_to_help_you_succeed: 'Nous sommes là pour vous aider à réussir',
    thank_you_for_choosing_us: 'Merci de nous avoir choisis',
    we_look_forward_to_helping_you_achieve_your_goals: 'Nous sommes impatients de vous aider à atteindre vos objectifs',
    together_we_can_achieve_great_things: 'Ensemble, nous pouvons réaliser de grandes choses',
    thank_you_for_your_trust: 'Merci de votre confiance',
    we_are_committed_to_your_success: 'Nous nous engageons à votre succès',
    together_we_will_build_a_brighter_future: 'Ensemble, nous construirons un avenir meilleur',

    // Homepage
    hero_title: 'Accédez à des milliers de sujets d\'examen avec',
    hero_subtitle: 'Préparez-vous au succès avec notre vaste collection de sujets d\'examen passés et de matériel d\'étude pour les systèmes éducatifs francophones et anglophones en Afrique.',
    explore_exams: 'Explorer les examens',
    get_started_free: 'Commencer gratuitement',
    sign_in: 'Se connecter',
    free_no_commitment: 'Gratuit, sans engagement',
    exam_papers: 'Sujets d\'examen',
    active_students: 'Étudiants actifs',
    schools: 'Écoles',
    satisfaction: 'Satisfaction',
    how_it_works: 'Comment ça marche',
    how_it_works_subtitle: 'Commencez votre parcours d\'apprentissage en quatre étapes simples',
    step_1_title: 'Créer un compte',
    step_1_desc: 'Inscrivez-vous gratuitement et accédez à notre plateforme',
    step_2_title: 'Choisir votre niveau',
    step_2_desc: 'Sélectionnez votre classe et votre programme d\'études',
    step_3_title: 'Trouver les examens',
    step_3_desc: 'Parcourez notre vaste bibliothèque de sujets',
    step_4_title: 'Commencer à pratiquer',
    step_4_desc: 'Téléchargez et étudiez à votre rythme',
    why_choose: 'Pourquoi choisir Yimaprof ?',
    why_choose_subtitle: 'Tout ce dont vous avez besoin pour réussir vos examens',
    advanced_search: 'Recherche avancée',
    advanced_search_desc: 'Trouvez facilement les examens par matière, année et niveau',
    offline_access: 'Accès hors ligne',
    offline_access_desc: 'Téléchargez et étudiez n\'importe où, n\'importe quand',
    community_desc: 'Rejoignez une communauté d\'apprenants et partagez des idées',
    multilingual: 'Multilingue',
    multilingual_desc: 'Disponible en français et en anglais',
    francophone: 'Francophone',
    anglophone: 'Anglophone',
    cta_title: 'Prêt à commencer votre parcours d\'apprentissage ?',
    cta_subtitle: 'Rejoignez des milliers d\'étudiants qui réussissent avec Yimaprof',
    explore_now: 'Explorer maintenant',
    create_account: 'Créer un compte',
    view_subscriptions: 'Voir les abonnements',

    // Admin Page
    admin_dashboard: 'Tableau de bord administrateur',
    platform_management: 'Gestion de la plateforme et analytiques',
    admin_access: 'Accès administrateur',
    overview: 'Vue d\'ensemble',
    users: 'Utilisateurs',
    classes: 'Classes',
    system_configuration: 'Configuration système',
    establishments: 'Établissements',
    subjects: 'Matières',
    periods: 'Périodes/Trimestres',
    academic_years: 'Années académiques',
    exam_types: 'Types d\'examens',
    durations: 'Durées',
    plans: 'Plans',
    subscriptions: 'Abonnements',
    transactions: 'Transactions',
    platform_overview: 'Aperçu de la plateforme',
    total_revenue: 'Revenu total',
    updated_realtime: 'Mis à jour en temps réel',
    active_users: 'Utilisateurs actifs',
    last_30_days: '30 derniers jours',
    platform_health: 'Santé de la plateforme',
    excellent: 'Excellent',
    quick_navigation: 'Navigation rapide',
    quick_nav_desc: 'Utilisez le menu de navigation pour gérer différentes sections :',
    users_manage_desc: 'Gérer les comptes utilisateurs et les rôles',
    manage_exams: 'Gérer les épreuves',
    exams_manage_desc: 'Opérations CRUD pour les sujets d\'examen',
    classes_manage_desc: 'Gérer les classes éducatives',
    plans_manage_desc: 'Gestion des plans d\'abonnement',
    subscriptions_manage_desc: 'Voir les abonnements actifs',
    transactions_manage_desc: 'Historique des transactions financières',
    please_sign_in_admin: 'Veuillez vous connecter pour accéder au panneau d\'administration',
    loading_admin_panel: 'Chargement du panneau d\'administration...',
    access_denied: 'Accès refusé',
    no_admin_privileges: 'Vous n\'avez pas les privilèges d\'administrateur pour accéder à cette page.',
    access_denied_desc: 'Vous n\'avez pas les privilèges d\'administrateur',
    
    // User Management
    user_management: 'Gestion des utilisateurs',
    joined: 'Inscrit le',
    remove_admin: 'Retirer Admin',
    make_admin: 'Rendre Admin',
    
    // Class Management
    class_management: 'Gestion des classes',
    add_class: 'Ajouter une classe',
    edit_class: 'Modifier la classe',
    add_new_class: 'Ajouter une nouvelle classe',
    display_name: 'Nom d\'affichage',
    internal_name: 'Nom interne',
    delete_confirm_class: 'Êtes-vous sûr de vouloir supprimer cette classe ? Cela affectera tous les examens associés.',
    created: 'Créé',
    
    // Subscription Plan Management
    subscription_plan_management: 'Gestion des plans d\'abonnement',
    add_plan: 'Ajouter un plan',
    edit_subscription_plan: 'Modifier le plan d\'abonnement',
    add_new_subscription_plan: 'Ajouter un nouveau plan d\'abonnement',
    plan_name: 'Nom du plan',
    duration_days: 'Durée (jours)',
    max_downloads: 'Téléchargements max',
    max_downloads_hint: '999999 pour illimité',
    features_placeholder: 'Accès aux examens du curriculum français\nVoir les corrections et solutions\nTélécharger les sujets d\'examen',
    deactivate: 'Désactiver',
    activate: 'Activer',
    unlimited: 'Illimité',
    delete_confirm_plan: 'Êtes-vous sûr de vouloir supprimer ce plan d\'abonnement ? Cela affectera tous les abonnements associés.',
    
    // Active Subscriptions
    active_subscriptions: 'Abonnements actifs',
    started: 'Commencé',
    expires: 'Expire',
    auto_renew: 'Renouvellement auto',
    days_left: 'jours restants',
    cancel_subscription: 'Annuler',
    cancel_confirm_subscription: 'Êtes-vous sûr de vouloir annuler cet abonnement ?',
    
    // Subscriptions Page
    choose_your_plan: 'Choisissez votre plan',
    subscription_page_desc: 'Sélectionnez le plan parfait pour vos besoins éducatifs. Accédez à des milliers de sujets d\'examen et de corrections.',
    current_subscription: 'Abonnement actuel',
    referred_by_someone: 'Référé par quelqu\'un ?',
    referral_username: 'Nom d\'utilisateur de parrainage (Optionnel)',
    enter_username: 'Entrer le nom d\'utilisateur',
    valid_referral: 'Parrainage valide',
    cannot_refer_yourself: 'Vous ne pouvez pas vous parrainer vous-même',
    username_not_found: 'Nom d\'utilisateur introuvable',
    reset_password: 'Réinitialiser le mot de passe',
    new_password: 'Nouveau mot de passe',
    confirm_new_password: 'Confirmer le nouveau mot de passe',
    password_reset_success: 'Mot de passe réinitialisé avec succès',
    password_reset_error: 'Erreur lors de la réinitialisation',
    passwords_dont_match: 'Les mots de passe ne correspondent pas',
    password_too_weak: 'Le mot de passe doit contenir au moins 6 caractères',
    invalid_reset_link: 'Lien de réinitialisation invalide ou expiré',
    request_new_reset_link: 'Demander un nouveau lien',
    enter_new_password: 'Entrez votre nouveau mot de passe',
    forgot_password: 'Mot de passe oublié',
    forgot_password_description: 'Entrez votre adresse email et nous vous enverrons un lien pour réinitialiser votre mot de passe',
    reset_email_sent_description: 'Un email a été envoyé avec les instructions pour réinitialiser votre mot de passe',
    check_email_for_reset_link: 'Vérifiez votre boîte mail pour le lien de réinitialisation',
    back_to_login: 'Retour à la connexion',
    send_reset_link: 'Envoyer le lien de réinitialisation',
    most_popular: 'Le plus populaire',
    per_month: '/mois',
    current_plan: 'Plan actuel',
    upgrade: 'Améliorer',
    downgrade: 'Rétrograder',
    switch_plan: 'Changer de plan',
    subscribe_to_plan: 'S\'abonner maintenant',
    support_them: 'Entrez le nom d\'utilisateur de la personne qui vous a référé pour la soutenir',
    all_plans_include: 'Tous les plans incluent l\'accès aux sujets d\'examen, aux corrections et aux mises à jour régulières du contenu. Aucun paiement requis - activation instantanée !',
    processing: 'Traitement en cours...',
    active: 'Actif',
    
    // Payment Processing
    payment_processing: 'Traitement du paiement',
    payment_processing_desc: 'Veuillez compléter le paiement sur votre appareil mobile.',
    payment_success: 'Paiement réussi !',
    payment_success_desc: 'Votre abonnement a été activé avec succès.',
    payment_failed: 'Paiement échoué',
    payment_failed_desc: 'Votre paiement n\'a pas pu être traité. Veuillez réessayer.',
    check: 'Vérification',
    of: 'de',
    cancel_go_back: 'Annuler et retourner',
    go_to_subscriptions: 'Aller aux abonnements',
    go_to_exams: 'Aller aux examens',
    try_again: 'Réessayer',
    back_to_plans: 'Retour aux plans',
    check_phone_payment: 'Vérifiez votre téléphone pour la notification de paiement',
    what_to_do_next: 'Quoi faire ensuite :',
    check_phone_notification: 'Vérifiez votre téléphone pour une notification de paiement',
    enter_pin: 'Entrez votre PIN mobile money lorsque demandé',
    confirm_amount: 'Confirmez le montant du paiement',
    wait_confirmation: 'Attendez la confirmation',
    
    // Evaluation Mode
    evaluation_results: 'Résultats de l\'évaluation',
    correct_answers: 'Questions correctes',
    score: 'Score',
    retry_evaluation: 'Recommencer l\'évaluation',
    submit_evaluation: 'Soumettre l\'évaluation',
    answer_at_least_one: 'Répondez à au moins une question pour soumettre',
    evaluation_submitted: 'Évaluation soumise',
    your_score: 'Votre score',
    
    // Transaction History
    transaction_history: 'Historique des transactions',
    date: 'Date',
    amount: 'Montant',
    provider: 'Fournisseur',
    reference: 'Référence',
    
    // Exam Manager
    create_exam: 'Créer un examen',
    edit_exam: 'Modifier un examen',
    exam_details: 'Détails de l\'examen',
    exam_title: 'Titre de l\'examen',
    year: 'Année',
    exam_type: 'Type d\'examen',
    class: 'Classe',
    select_class: 'Sélectionner une classe',
    period: 'Période',
    language: 'Langue',
    duration: 'Durée (minutes)',
    enter_tags: 'Entrer les mots-clés (séparés par des virgules)',
    content_editor: 'Éditeur de contenu',
    form_builder: 'Créateur de formulaire',
    json_editor: 'Éditeur JSON',
    pdf_upload: 'Télécharger PDF',
    upload_pdf: 'Télécharger le fichier PDF',
    choose_file: 'Choisir un fichier',
    no_file_chosen: 'Aucun fichier choisi',
    upload: 'Télécharger',
    copy_template: 'Copier le modèle',
    validate_json: 'Valider JSON',
    json_valid: 'JSON valide',
    json_invalid: 'JSON invalide',
    preview: 'Aperçu',
    save_draft: 'Enregistrer le brouillon',
    publish_exam: 'Publier l\'examen',
    publish_and_create_another: 'Publier et créer un autre',
    click_to_edit: 'Cliquez sur n\'importe quel texte pour modifier',
    pdf_preview: 'Aperçu PDF',
    add_content_below: 'Ajoutez du contenu ci-dessous pour voir l\'aperçu',

    // About Page
    about: 'À propos',
    about_title: 'À propos de Yimaprof',
    about_description: 'Yimaprof est une plateforme éducative dédiée à l\'excellence académique en Afrique. Nous rendons l\'éducation accessible en fournissant des ressources d\'examen de qualité aux étudiants des systèmes francophones et anglophones.',
    our_mission: 'Notre Mission',
    mission_description: 'Notre mission est de démocratiser l\'accès aux ressources éducatives de qualité en Afrique. Nous croyons que chaque étudiant mérite les meilleures opportunités de réussir ses examens et d\'atteindre son plein potentiel académique.',
    our_values: 'Nos Valeurs',
    excellence: 'Excellence',
    excellence_desc: 'Nous nous engageons à fournir des ressources de la plus haute qualité',
    accessibility_desc: 'Rendre l\'éducation accessible à tous les étudiants',
    diversity_desc: 'Célébrer la diversité des systèmes éducatifs africains',
    innovation: 'Innovation',
    innovation_desc: 'Utiliser la technologie pour transformer l\'apprentissage',
    our_story: 'Notre Histoire',
    story_paragraph_1: 'Yimaprof a été fondée avec une vision simple mais puissante : donner à chaque étudiant africain l\'accès aux ressources dont il a besoin pour réussir. Nous avons commencé par reconnaître le défi auquel sont confrontés de nombreux étudiants pour accéder aux sujets d\'examen passés et aux matériels d\'étude.',
    story_paragraph_2: 'Depuis notre lancement, nous sommes devenus la plateforme de référence pour les sujets d\'examen dans les systèmes éducatifs francophones et anglophones. Notre collection s\'est développée pour inclure des milliers de sujets couvrant plusieurs années, niveaux et matières.',
    story_paragraph_3: 'Aujourd\'hui, Yimaprof sert des milliers d\'étudiants dans toute l\'Afrique, les aidant à se préparer efficacement pour leurs examens. Nous continuons d\'innover et d\'élargir nos offres pour mieux servir la communauté éducative.',
    join_us_description: 'Rejoignez notre communauté grandissante d\'étudiants et commencez votre parcours vers la réussite académique dès aujourd\'hui.',

    // Contact Page
    contact_us: 'Contactez-nous',
    contact_description: 'Vous avez des questions ou besoin d\'aide ? Notre équipe est là pour vous aider. Contactez-nous et nous vous répondrons dans les plus brefs délais.',
    send_message: 'Envoyer un message',
    first_name: 'Prénom',
    last_name: 'Nom',
    contact_info: 'Informations de contact',
    hours: 'Heures d\'ouverture',
    support_hours: 'Lundi - Vendredi : 8h00 - 18h00 (WAT)',
    faq_title: 'Questions fréquentes',
    faq_1_question: 'Comment puis-je accéder aux examens ?',
    faq_1_answer: 'Créez simplement un compte gratuit et parcourez notre bibliothèque d\'examens. Certains examens nécessitent un abonnement premium.',
    faq_2_question: 'Les corrections sont-elles disponibles ?',
    faq_2_answer: 'Oui, de nombreux examens incluent des corrections détaillées et des schémas de notation pour vous aider à comprendre les solutions.',
    faq_3_question: 'Puis-je télécharger les examens ?',
    faq_3_answer: 'Oui, les abonnés peuvent télécharger les examens pour étudier hors ligne à tout moment.',

    // Privacy Page
    privacy_intro: 'Yimaprof ("nous", "notre" ou "nos") exploite le site web yimaprof.com et l\'application mobile Yimaprof (ci-après dénommés le "Service"). Cette page vous informe de nos politiques concernant la collecte, l\'utilisation et la divulgation des données personnelles lorsque vous utilisez notre Service.',
    privacy_data_collection_title: 'Collecte et utilisation des données',
    privacy_data_collection: 'Nous collectons plusieurs types d\'informations à des fins diverses pour fournir et améliorer notre Service pour vous.',
    privacy_types_title: 'Types de données collectées',
    privacy_personal_data: 'Lors de l\'utilisation de notre Service, nous pouvons vous demander de nous fournir certaines informations personnellement identifiables qui peuvent être utilisées pour vous contacter ou vous identifier ("Données personnelles"). Les informations personnellement identifiables peuvent inclure, mais sans s\'y limiter : adresse e-mail, prénom et nom, numéro de téléphone, cookies et données d\'utilisation.',
    privacy_usage_data: 'Nous pouvons également collecter des informations sur la façon dont le Service est consulté et utilisé ("Données d\'utilisation"). Ces Données d\'utilisation peuvent inclure des informations telles que l\'adresse de protocole Internet de votre ordinateur (par exemple, adresse IP), le type de navigateur, la version du navigateur, les pages de notre Service que vous visitez, l\'heure et la date de votre visite, le temps passé sur ces pages, les identifiants uniques de l\'appareil et d\'autres données de diagnostic.',
    privacy_use_title: 'Utilisation des données',
    privacy_use: 'Yimaprof utilise les données collectées à diverses fins : fournir et maintenir notre Service, vous informer des modifications de notre Service, vous permettre de participer aux fonctionnalités interactives de notre Service lorsque vous choisissez de le faire, fournir un support client, recueillir des analyses ou des informations précieuses afin que nous puissions améliorer notre Service, surveiller l\'utilisation de notre Service, détecter, prévenir et résoudre les problèmes techniques.',
    privacy_data_sharing_title: 'Partage des données',
    privacy_data_sharing: 'Nous ne vendons, n\'échangeons ni ne louons vos informations personnelles à des tiers. Nous pouvons partager des informations agrégées démographiques non liées à des informations personnelles avec nos partenaires commerciaux et nos annonceurs.',
    privacy_security_title: 'Sécurité des données',
    privacy_security: 'La sécurité de vos données est importante pour nous, mais n\'oubliez pas qu\'aucune méthode de transmission sur Internet ou méthode de stockage électronique n\'est sûre à 100%. Bien que nous nous efforcions d\'utiliser des moyens commercialement acceptables pour protéger vos Données personnelles, nous ne pouvons garantir leur sécurité absolue.',
    privacy_rights_title: 'Vos droits',
    privacy_rights: 'Vous avez le droit d\'accéder, de mettre à jour ou de supprimer les informations que nous avons sur vous. Vous pouvez également nous contacter pour exercer ces droits.',
    privacy_cookies_title: 'Cookies',
    privacy_cookies: 'Nous utilisons des cookies et des technologies de suivi similaires pour suivre l\'activité sur notre Service et nous conservons certaines informations. Vous pouvez demander à votre navigateur de refuser tous les cookies ou d\'indiquer quand un cookie est envoyé.',
    privacy_changes_title: 'Modifications de cette politique',
    privacy_changes: 'Nous pouvons mettre à jour notre Politique de confidentialité de temps à autre. Nous vous informerons de toute modification en publiant la nouvelle Politique de confidentialité sur cette page et en mettant à jour la date de "dernière mise à jour".',
    privacy_contact_title: 'Contactez-nous',
    privacy_contact: 'Si vous avez des questions sur cette Politique de confidentialité, veuillez nous contacter à privacy@yima.cm',

    // Terms Page
    terms_last_updated: 'Dernière mise à jour : Janvier 2025',
    terms_acceptance_title: 'Acceptation des conditions',
    terms_acceptance: 'En accédant et en utilisant Yimaprof, vous acceptez d\'être lié par ces Conditions d\'utilisation. Si vous n\'acceptez pas ces conditions, veuillez ne pas utiliser notre Service.',
    terms_description_title: 'Description du service',
    terms_description: 'Yimaprof fournit une plateforme en ligne donnant accès aux sujets d\'examen, aux matériels d\'étude et aux ressources éducatives connexes pour les systèmes éducatifs francophones et anglophones en Afrique.',
    terms_user_accounts_title: 'Comptes utilisateurs',
    terms_user_accounts: 'Pour accéder à certaines fonctionnalités du Service, vous devrez créer un compte. Vous acceptez de :',
    terms_account_accuracy: 'Fournir des informations exactes, actuelles et complètes',
    terms_account_security: 'Maintenir la sécurité de votre mot de passe et de votre compte',
    terms_account_responsibility: 'Assumer la responsabilité de toutes les activités qui se produisent sous votre compte',
    terms_account_age: 'Avoir au moins 13 ans ou avoir le consentement parental',
    terms_use_rules_title: 'Règles d\'utilisation',
    terms_use_rules: 'Vous acceptez de ne pas :',
    terms_rule_legal: 'Utiliser le Service à des fins illégales',
    terms_rule_respect: 'Violer les droits de propriété intellectuelle de tiers',
    terms_rule_no_sharing: 'Partager votre compte avec d\'autres',
    terms_rule_no_reverse: 'Tenter d\'effectuer de la rétro-ingénierie du Service',
    terms_rule_no_automated: 'Utiliser des systèmes automatisés pour accéder au Service',
    terms_intellectual_property_title: 'Propriété intellectuelle',
    terms_intellectual_property: 'Tout le contenu disponible sur Yimaprof, y compris les sujets d\'examen, les textes, les graphiques et le code, est protégé par les lois sur les droits d\'auteur et appartient à Yimaprof ou à ses concédants de licence.',
    terms_subscriptions_title: 'Abonnements et paiements',
    terms_subscriptions: 'Certaines fonctionnalités nécessitent un abonnement payant. Vous acceptez que :',
    terms_subscription_billing: 'Les abonnements sont facturés à l\'avance sur une base périodique',
    terms_subscription_renewal: 'Les abonnements se renouvellent automatiquement sauf annulation',
    terms_subscription_cancellation: 'Vous pouvez annuler à tout moment',
    terms_subscription_refund: 'Les remboursements sont traités selon notre politique de remboursement',
    terms_termination_title: 'Résiliation',
    terms_termination: 'Nous nous réservons le droit de suspendre ou de résilier votre compte en cas de violation de ces Conditions d\'utilisation ou pour toute autre raison que nous jugeons nécessaire.',
    terms_disclaimer_title: 'Clause de non-responsabilité',
    terms_disclaimer: 'Le Service est fourni "tel quel" sans garanties d\'aucune sorte. Nous ne garantissons pas que le Service sera ininterrompu, sécurisé ou exempt d\'erreurs.',
    terms_limitation_title: 'Limitation de responsabilité',
    terms_limitation: 'Yimaprof ne sera pas responsable des dommages indirects, accessoires, spéciaux, consécutifs ou punitifs résultant de votre utilisation ou de votre incapacité à utiliser le Service.',
    terms_governing_law_title: 'Droit applicable',
    terms_governing_law: 'Ces Conditions sont régies par les lois du Cameroun. Tout litige sera résolu devant les tribunaux du Cameroun.',
    terms_changes_title: 'Modifications des conditions',
    terms_changes: 'Nous pouvons modifier ces Conditions à tout moment. Nous vous informerons des modifications importantes par e-mail ou par une notification sur le Service.',
    terms_contact_title: 'Contact',
    terms_contact: 'Pour toute question concernant ces Conditions, veuillez nous contacter à :',
    
    // Notifications - detailed
    unreadNotifications: 'non lus',
    noNotifications: 'Aucune notification',
    noNotificationsDesc: 'Vous n\'avez pas encore de notifications',
    viewAllNotifications: 'Voir toutes les notifications',
    markAllRead: 'Tout marquer comme lu',
    allTypes: 'Tous les types',
    subscriptionExpiry: 'Expiration d\'abonnement',
    paymentConfirmed: 'Paiement confirmé',
    adminMessage: 'Message administrateur',
    accountActivity: 'Activité du compte',
    allNotifications: 'Toutes',
    readNotifications: 'Lues',
    loadMore: 'Charger plus',
    
    // Admin Notification Composer
    composeNotification: 'Composer une notification',
    composeNotificationDesc: 'Créer et envoyer des notifications aux utilisateurs',
    notificationTitle: 'Titre de la notification',
    notificationMessage: 'Message de la notification',
    recipientFilters: 'Filtres de destinataires',
    sendToAllUsers: 'Envoyer à tous les utilisateurs',
    subscriptionPlans: 'Plans d\'abonnement',
    subscriptionStatus: 'Statut d\'abonnement',
    classLevels: 'Niveaux de classe',
    activeStatus: 'Actif',
    pendingStatus: 'En attente',
    expiredStatus: 'Expiré',
    canceledStatus: 'Annulé',
    lowPriority: 'Faible',
    normalPriority: 'Normal',
    highPriority: 'Élevé',
    actionUrl: 'URL d\'action',
    optional: 'optionnel',
    previewNotification: 'Aperçu',
    sendNotification: 'Envoyer la notification',
    sending: 'Envoi en cours',
    notificationPreview: 'Aperçu de la notification',
    previewDesc: 'Voici à quoi ressemblera votre notification',
    notificationSent: 'Notification envoyée à',
    recipients: 'destinataires',
    notificationSendFailed: 'Échec de l\'envoi de la notification',
    noRecipientsFound: 'Aucun destinataire trouvé avec les filtres sélectionnés',
    fillRequiredFields: 'Veuillez remplir tous les champs obligatoires',
    allUsers: 'Tous les utilisateurs',
    
    // Write to Us / Feedback
    write_to_us: 'Écrivez-nous',
    feedback_intro: 'Nous accordons une grande importance à votre avis ! Utilisez ce formulaire pour partager vos commentaires, suggestions, demandes ou avis. Vos réflexions nous aident à nous améliorer et à mieux vous servir.',
    share_feedback: 'Partagez vos commentaires',
    feedback_form_desc: 'Dites-nous ce que vous pensez. Votre retour est important pour nous.',
    your_feedback: 'Vos commentaires',
    feedback_placeholder: 'Partagez vos réflexions, suggestions ou commentaires ici...',
    send_feedback: 'Envoyer les commentaires',
    character_count: '{count} / 1000 caractères',
    feedback_success_title: 'Merci pour vos commentaires !',
    feedback_success: 'Notre équipe examinera vos commentaires bientôt.',
    feedback_error_title: 'Erreur',
    feedback_error: 'Échec de l\'envoi des commentaires. Veuillez réessayer.',
    login_to_feedback: 'Veuillez vous connecter pour nous envoyer vos commentaires.',
    feedback_privacy_note: 'Vos commentaires sont confidentiels et nous aident à améliorer nos services.',
    login_required: 'Connexion requise',
    
    // Admin - Feedback Management
    user_feedback: 'Retours d\'utilisateurs',
    manage_user_feedback: 'Consulter et gérer les commentaires des utilisateurs',
    feedback_status_new: 'Nouveau',
    feedback_status_reviewed: 'Examiné',
    feedback_status_replied: 'Répondu',
    view_details: 'Voir les détails',
    feedback_details: 'Détails des commentaires',
    view_full_feedback: 'Consultez les commentaires complets et mettez à jour le statut',
    feedback_content: 'Contenu des commentaires',
    update_status: 'Mettre à jour le statut',
    status_updated: 'Statut mis à jour',
    feedback_status_updated: 'Le statut des commentaires a été mis à jour avec succès',
    failed_to_load_feedback: 'Échec du chargement des commentaires',
    failed_to_update_status: 'Échec de la mise à jour du statut',
    unknown_user: 'Utilisateur inconnu',
    no_email: 'Pas d\'email',
    all: 'Tous',
    refresh: 'Actualiser',
    
    // Dashboard
    profilePhoto: 'Photo de profil',
    managePersonalInfo: 'Gérer vos informations personnelles',
    editProfile: 'Modifier le profil',
    saveChanges: 'Enregistrer les modifications',
    firstName: 'Prénom',
    lastName: 'Nom',
    uploadPhoto: 'Télécharger une photo',
    uploading: 'Téléchargement...',
    saving: 'Enregistrement...',
    profileUpdated: 'Profil mis à jour avec succès',
    profileError: 'Erreur lors de la mise à jour du profil',
    statistics: 'Statistiques',
    learningProgress: 'Votre progression d\'apprentissage',
    examsCompleted: 'Examens terminés',
    totalPoints: 'Points totaux',
    averageScore: 'Score moyen',
    studyStreak: 'Jours consécutifs',
    currentPlan: 'Votre plan et statut actuel',
    expiresOn: 'Expire le',
    free: 'Gratuit',
    managePlan: 'Gérer l\'abonnement',
    recentExams: 'Examens récents',
    latestPractice: 'Vos dernières sessions de pratique',
    noExams: 'Aucun examen récent',
    viewAll: 'Voir tout',
    
    // Settings
    settingsTitle: 'Paramètres',
    manageAccountSettings: 'Gérer vos paramètres de compte et préférences',
    accountSettings: 'Paramètres du compte',
    selectClassLevel: 'Sélectionner le niveau',
    preferredLanguage: 'Langue préférée pour le contenu',
    notificationPreferences: 'Préférences de notification',
    receiveEmailNotif: 'Recevoir les notifications par email',
    emailSubscriptionExpiry: 'Email - Expiration d\'abonnement',
    emailPaymentConfirmed: 'Email - Paiement confirmé',
    emailAdminMessages: 'Email - Messages admin',
    inAppNotifications: 'Notifications dans l\'application',
    inAppSubscriptionExpiry: 'App - Expiration d\'abonnement',
    inAppPaymentConfirmed: 'App - Paiement confirmé',
    inAppAdminMessages: 'App - Messages admin',
    inAppAccountActivity: 'App - Activité du compte',
    interfaceLanguage: 'Langue de l\'interface',
    chooseInterfaceLanguage: 'Choisissez votre langue d\'interface préférée',
    accountSecurity: 'Gérer la sécurité de votre compte',
    changePassword: 'Changer le mot de passe',
    twoFactorAuth: 'Authentification à deux facteurs',
    extraSecurity: 'Ajouter une couche de sécurité supplémentaire',
    settingsSaved: 'Paramètres enregistrés avec succès',
    settingsError: 'Erreur lors de l\'enregistrement des paramètres',
    
    // Exam Manager
    examSchool: 'École/Établissement',
    examAddNewSchool: 'Ajouter une nouvelle école',
    examSubject: 'Matière',
    examAddNewSubject: 'Ajouter une nouvelle matière',
    examType: 'Type d\'Épreuve',
    examDuringYear: 'Évaluation en Cours d\'Année',
    examEndTerm: 'Évaluation de Fin de Période',
    examAcademicYear: 'Année Scolaire',
    examAddNewYear: 'Ajouter une nouvelle année',
    examPeriod: 'Période/Trimestre',
    examDuration: 'Durée',
    examAddCustomDuration: 'Ajouter une durée personnalisée',
    examSelectSchool: 'Sélectionner une école',
    examSelectSubject: 'Sélectionner une matière',
    examSelectExamType: 'Sélectionner le type d\'épreuve',
    examSelectYear: 'Sélectionner l\'année',
    examSelectPeriod: 'Sélectionner la période',
    examSelectDuration: 'Sélectionner la durée',
    examEnglishName: 'Nom Anglais',
    examFrenchName: 'Nom Français',
    examSchoolName: 'Nom de l\'École',
    examYearFormat: 'Format d\'Année (ex: 2024-2025)',
    examDurationMinutes: 'Durée (minutes)',
    examAddingSchool: 'Ajouter une Nouvelle École',
    examAddingSubject: 'Ajouter une Nouvelle Matière',
    examAddingYear: 'Ajouter une Nouvelle Année Scolaire',
    examAddingDuration: 'Ajouter une Nouvelle Durée',
    examSuccessSchool: 'École ajoutée avec succès',
    examSuccessSubject: 'Matière ajoutée avec succès',
    examSuccessYear: 'Année scolaire ajoutée avec succès',
    examSuccessDuration: 'Durée ajoutée avec succès',
    examErrorAdding: 'Échec de l\'ajout de l\'élément',
    
    // Admin Exams Page
    exam_management: 'Gestion des épreuves',
    search_exams: 'Rechercher des épreuves...',
    language_filter: 'Langue',
    year_filter: 'Année',
    all_years: 'Toutes les années',
    subject_filter: 'Matière',
    all_subjects: 'Toutes les matières',
    class_filter: 'Classe',
    all_classes: 'Toutes les classes',
    school_filter: 'École',
    all_schools: 'Toutes les écoles',
    no_school_set: 'Aucune école définie',
    status_filter: 'Statut',
    all_status: 'Tous les statuts',
    published: 'Publié',
    draft: 'Brouillon',
    clear_filters: 'Effacer les filtres',
    please_sign_in_page: 'Veuillez vous connecter pour accéder à cette page.',
    back_to_admin: 'Retour Admin',
    filters: 'Filtres',
    add_exam: 'Ajouter',
    hide_filters: 'Masquer',
    no_exams_found: 'Aucune épreuve trouvée correspondant à vos critères',
    previous: 'Précédent',
    next: 'Suivant',
    showing_exams: 'Affichage de',
    of_exams: 'sur',
    
    // Footer
    about_yima: 'Yimaprof est une plateforme éducative dédiée à l\'excellence académique en Afrique. Nous rendons l\'éducation accessible en fournissant des ressources d\'examen de qualité.',
    platform: 'Plateforme',
    company: 'Entreprise',
    stay_updated: 'Restez informé',
    newsletter_desc: 'Abonnez-vous à notre newsletter pour recevoir les dernières mises à jour et les nouveaux examens.',
    enter_email: 'Entrez votre email',
    rights_reserved: 'Tous droits réservés.',
  },
  en: {
    navigation: 'Navigation',
    homepage: 'Homepage',
    features: 'Features',
    pricing: 'Pricing',
    contact: 'Contact',
    login: 'Login',
    logout: 'Logout',
    register: 'Register',
    dashboard: 'Dashboard',
    profile: 'Profile',
    settings: 'Settings',
    welcome: 'Welcome',
    description: 'Description',
    get_started: 'Get Started',
    about_us: 'About Us',
    our_team: 'Our Team',
    services: 'Services',
    testimonials: 'Testimonials',
    faq: 'FAQ',
    blog: 'Blog',
    news: 'News',
    careers: 'Careers',
    terms: 'Terms of Use',
    privacy: 'Privacy Policy',
    cookie: 'Cookie Policy',
    support: 'Support',
    help: 'Help',
    documentation: 'Documentation',
    api: 'API',
    community: 'Community',
    forum: 'Forum',
    chat: 'Chat',
    email: 'Email',
    phone: 'Phone',
    address: 'Address',
    copyright: 'Copyright',
    all_rights_reserved: 'All Rights Reserved',
    home: 'Home',
    more: 'More',
    exams: 'Exams',
    practice: 'Practice',
    quizzes: 'Quizzes',
    lessons: 'Lessons',
    courses: 'Courses',
    curriculum: 'Curriculum',
    teachers: 'Teachers',
    students: 'Students',
    grades: 'Grades',
    calendar: 'Calendar',
    messages: 'Messages',
    notifications: 'Notifications',
    tasks: 'Tasks',
    files: 'Files',
    resources: 'Resources',
    tools: 'Tools',
    reports: 'Reports',
    analytics: 'Analytics',
    performance: 'Performance',
    progress: 'Progress',
    results: 'Results',
    feedback: 'Feedback',
    survey: 'Survey',
    poll: 'Poll',
    events: 'Events',
    webinars: 'Webinars',
    workshops: 'Workshops',
    seminars: 'Seminars',
    conferences: 'Conferences',
    activities: 'Activities',
    achievements: 'Achievements',
    awards: 'Awards',
    certificates: 'Certificates',
    partners: 'Partners',
    sponsors: 'Sponsors',
    investors: 'Investors',
    clients: 'Clients',
    projects: 'Projects',
    products: 'Products',
    solutions: 'Solutions',
    services_offered: 'Services Offered',
    case_studies: 'Case Studies',
    success_stories: 'Success Stories',
    mission: 'Mission',
    vision: 'Vision',
    values: 'Values',
    team: 'Team',
    leadership: 'Leadership',
    board_of_directors: 'Board of Directors',
    advisors: 'Advisors',
    careers_at: 'Careers at',
    open_positions: 'Open Positions',
    apply_now: 'Apply Now',
    internships: 'Internships',
    volunteering: 'Volunteering',
    diversity: 'Diversity',
    inclusion: 'Inclusion',
    equity: 'Equity',
    accessibility: 'Accessibility',
    sustainability: 'Sustainability',
    impact: 'Impact',
    donate: 'Donate',
    volunteer: 'Volunteer',
    join_us: 'Join Us',
    subscribe: 'Subscribe',
    follow_us: 'Follow Us',
    share: 'Share',
    like: 'Like',
    comment: 'Comment',
    read_more: 'Read More',
    view_all: 'View All',
    latest_news: 'Latest News',
    featured_articles: 'Featured Articles',
    popular_topics: 'Popular Topics',
    categories: 'Categories',
    tags: 'Tags',
    archive: 'Archive',
    search: 'Search',
    no_results_found: 'No Results Found',
    error_404: 'Error 404',
    page_not_found: 'Page Not Found',
    back_to_home: 'Back to Home',
    loading: 'Loading',
    please_wait: 'Please Wait',
    submit: 'Submit',
    send: 'Send',
    reset: 'Reset',
    update: 'Update',
    delete: 'Delete',
    cancel: 'Cancel',
    save: 'Save',
    edit: 'Edit',
    add_new: 'Add New',
    create: 'Create',
    manage: 'Manage',
    view: 'View',
    details: 'Details',
    options: 'Options',
    actions: 'Actions',
    confirm: 'Confirm',
    are_you_sure: 'Are you sure?',
    yes: 'Yes',
    no: 'No',
    success: 'Success',
    error: 'Error',
    warning: 'Warning',
    information: 'Information',
    required_fields: 'Required Fields',
    invalid_email: 'Invalid Email',
    password_mismatch: 'Passwords do not match',
    password_length: 'Password must be at least 8 characters',
    username_exists: 'Username already exists',
    email_exists: 'Email already exists',
    login_failed: 'Login Failed',
    registration_successful: 'Registration Successful',
    password_reset_sent: 'Password reset email sent',
    password_reset_successful: 'Password reset successful',
    profile_updated: 'Profile Updated',
    data_saved: 'Data Saved',
    data_deleted: 'Data Deleted',
    item_added: 'Item Added',
    item_updated: 'Item Updated',
    item_deleted: 'Item Deleted',
    message_sent: 'Message Sent',
    subscription_successful: 'Subscription Successful',
    payment_successful: 'Payment Successful',
    order_placed: 'Order Placed',
    download_started: 'Download Started',
    file_uploaded: 'File Uploaded',
    task_completed: 'Task Completed',
    event_created: 'Event Created',
    award_received: 'Award Received',
    certificate_earned: 'Certificate Earned',
    thank_you: 'Thank You',
    congratulations: 'Congratulations',
    welcome_aboard: 'Welcome Aboard',
    get_in_touch: 'Get In Touch',
    send_us_a_message: 'Send Us a Message',
    your_name: 'Your Name',
    your_email: 'Your Email',
    subject: 'Subject',
    message: 'Message',
    i_agree_to_the: 'I agree to the',
    and: 'and',
    privacy_policy: 'privacy policy',
    terms_of_service: 'terms of service',
    sign_up_for_our_newsletter: 'Sign Up for Our Newsletter',
    enter_your_email: 'Enter Your Email',
    subscribe_now: 'Subscribe Now',
    stay_up_to_date: 'Stay Up To Date',
    never_miss_an_update: 'Never Miss an Update',
    we_respect_your_privacy: 'We Respect Your Privacy',
    unsubscribe_at_any_time: 'Unsubscribe at Any Time',
    learn_more: 'Learn More',
    explore: 'Explore',
    discover: 'Discover',
    browse: 'Papers',
    find_out_more: 'Find Out More',
    start_learning: 'Start Learning',
    improve_your_skills: 'Improve Your Skills',
    become_an_expert: 'Become an Expert',
    unlock_your_potential: 'Unlock Your Potential',
    achieve_your_goals: 'Achieve Your Goals',
    transform_your_life: 'Transform Your Life',
    invest_in_yourself: 'Invest in Yourself',
    join_our_community: 'Join Our Community',
    connect_with_experts: 'Connect With Experts',
    share_your_knowledge: 'Share Your Knowledge',
    get_inspired: 'Get Inspired',
    stay_motivated: 'Stay Motivated',
    celebrate_success: 'Celebrate Success',
    make_a_difference: 'Make a Difference',
    create_a_better_future: 'Create a Better Future',
    together_we_can: 'Together We Can',
    making_education_accessible: 'Making Education Accessible',
    empowering_learners_worldwide: 'Empowering Learners Worldwide',
    building_a_brighter_tomorrow: 'Building a Brighter Tomorrow',
    education_for_all: 'Education for All',
    a_world_of_knowledge: 'A World of Knowledge',
    your_path_to_success: 'Your Path to Success',
    the_future_of_learning: 'The Future of Learning',
    unlocking_human_potential: 'Unlocking Human Potential',
    transforming_lives_through_education: 'Transforming Lives Through Education',
    creating_opportunities_for_everyone: 'Creating Opportunities for Everyone',
    investing_in_the_next_generation: 'Investing in the Next Generation',
    inspiring_a_love_of_learning: 'Inspiring a Love of Learning',
    making_a_positive_impact: 'Making a Positive Impact',
    building_a_global_community: 'Building a Global Community',
    connecting_people_through_education: 'Connecting People Through Education',
    empowering_individuals_and_communities: 'Empowering Individuals and Communities',
    creating_a_more_equitable_world: 'Creating a More Equitable World',
    working_together_for_a_better_future: 'Working Together for a Better Future',
    join_us_on_this_journey: 'Join Us on This Journey',
    together_we_can_make_a_difference: 'Together We Can Make a Difference',
    thank_you_for_being_part_of_our_community: 'Thank You for Being Part of Our Community',
    we_appreciate_your_support: 'We Appreciate Your Support',
    together_we_are_making_a_difference: 'Together We Are Making a Difference',
    welcome_to_our_platform: 'Welcome to Our Platform',
    we_are_excited_to_have_you_with_us: 'We Are Excited to Have You With Us',
    let_s_start_learning_together: 'Let\'s Start Learning Together',
    we_are_here_to_help_you_succeed: 'We Are Here to Help You Succeed',
    thank_you_for_choosing_us: 'Thank You for Choosing Us',
    we_look_forward_to_helping_you_achieve_your_goals: 'We Look Forward to Helping You Achieve Your Goals',
    together_we_can_achieve_great_things: 'Together We Can Achieve Great Things',
    thank_you_for_your_trust: 'Thank You for Your Trust',
    we_are_committed_to_your_success: 'We Are Committed to Your Success',
    together_we_will_build_a_brighter_future: 'Together We Will Build a Brighter Future',

    // Homepage
    hero_title: 'Access Thousands of Exam Papers with',
    hero_subtitle: 'Prepare for success with our comprehensive collection of past exam papers and study materials for Francophone and Anglophone educational systems across Africa.',
    explore_exams: 'Explore Exams',
    get_started_free: 'Get Started Free',
    sign_in: 'Sign In',
    free_no_commitment: 'Free, no commitment',
    exam_papers: 'Exam Papers',
    active_students: 'Active Students',
    schools: 'Schools',
    satisfaction: 'Satisfaction',
    how_it_works: 'How It Works',
    how_it_works_subtitle: 'Start your learning journey in four simple steps',
    step_1_title: 'Create Account',
    step_1_desc: 'Sign up for free and access our platform',
    step_2_title: 'Choose Your Level',
    step_2_desc: 'Select your class and curriculum',
    step_3_title: 'Find Exams',
    step_3_desc: 'Browse our extensive library of papers',
    step_4_title: 'Start Practicing',
    step_4_desc: 'Download and study at your own pace',
    why_choose: 'Why Choose Yimaprof?',
    why_choose_subtitle: 'Everything you need to excel in your exams',
    advanced_search: 'Advanced Search',
    advanced_search_desc: 'Easily find exams by subject, year, and level',
    offline_access: 'Offline Access',
    offline_access_desc: 'Download and study anywhere, anytime',
    community_desc: 'Join a community of learners and share insights',
    multilingual: 'Multilingual',
    multilingual_desc: 'Available in French and English',
    francophone: 'Francophone',
    anglophone: 'Anglophone',
    cta_title: 'Ready to Start Your Learning Journey?',
    cta_subtitle: 'Join thousands of students succeeding with Yimaprof',
    explore_now: 'Explore Now',
    create_account: 'Create Account',
    view_subscriptions: 'View Subscriptions',

    // Admin Page
    admin_dashboard: 'Admin Dashboard',
    platform_management: 'Platform management and analytics',
    admin_access: 'Administrator access',
    overview: 'Overview',
    users: 'Users',
    classes: 'Classes',
    system_configuration: 'System Configuration',
    establishments: 'Schools/Establishments',
    subjects: 'Subjects',
    periods: 'Periods/Semesters',
    academic_years: 'Academic Years',
    exam_types: 'Exam Types',
    durations: 'Durations',
    plans: 'Plans',
    subscriptions: 'Subscriptions',
    transactions: 'Transactions',
    platform_overview: 'Platform Overview',
    total_revenue: 'Total Revenue',
    updated_realtime: 'Updated in real time',
    active_users: 'Active Users',
    last_30_days: 'Last 30 days',
    platform_health: 'Platform Health',
    excellent: 'Excellent',
    quick_navigation: 'Quick Navigation',
    quick_nav_desc: 'Use the navigation menu to manage different sections:',
    users_manage_desc: 'Manage user accounts and roles',
    manage_exams: 'Manage Exams',
    exams_manage_desc: 'CRUD operations for exam papers',
    classes_manage_desc: 'Manage educational classes',
    plans_manage_desc: 'Subscription plan management',
    subscriptions_manage_desc: 'View active subscriptions',
    transactions_manage_desc: 'Financial transaction history',
    please_sign_in_admin: 'Please sign in to access the admin panel',
    loading_admin_panel: 'Loading admin panel...',
    access_denied: 'Access Denied',
    no_admin_privileges: 'You do not have administrator privileges to access this page.',
    access_denied_desc: 'You do not have administrator privileges',
    
    // User Management
    user_management: 'User Management',
    joined: 'Joined',
    remove_admin: 'Remove Admin',
    make_admin: 'Make Admin',
    
    // Class Management
    class_management: 'Class Management',
    add_class: 'Add Class',
    edit_class: 'Edit Class',
    add_new_class: 'Add New Class',
    display_name: 'Display Name',
    internal_name: 'Internal Name',
    delete_confirm_class: 'Are you sure you want to delete this class? This will affect all associated exams.',
    created: 'Created',
    
    // Subscription Plan Management
    subscription_plan_management: 'Subscription Plan Management',
    add_plan: 'Add Plan',
    edit_subscription_plan: 'Edit Subscription Plan',
    add_new_subscription_plan: 'Add New Subscription Plan',
    plan_name: 'Plan Name',
    duration_days: 'Duration (days)',
    max_downloads: 'Max Downloads',
    max_downloads_hint: '999999 for unlimited',
    features_placeholder: 'Access to French curriculum exams\nView corrections and solutions\nDownload exam papers',
    deactivate: 'Deactivate',
    activate: 'Activate',
    unlimited: 'Unlimited',
    delete_confirm_plan: 'Are you sure you want to delete this subscription plan? This will affect all associated subscriptions.',
    
    // Active Subscriptions
    active_subscriptions: 'Active Subscriptions',
    started: 'Started',
    expires: 'Expires',
    auto_renew: 'Auto Renew',
    days_left: 'days left',
    cancel_subscription: 'Cancel',
    cancel_confirm_subscription: 'Are you sure you want to cancel this subscription?',
    
    // Subscriptions Page
    choose_your_plan: 'Choose Your Plan',
    subscription_page_desc: 'Select the perfect plan for your educational needs. Access thousands of exam papers and corrections.',
    current_subscription: 'Current Subscription',
    referred_by_someone: 'Referred by someone?',
    referral_username: 'Referral Username (Optional)',
    enter_username: 'Enter username',
    valid_referral: 'Valid referral',
    cannot_refer_yourself: 'You cannot refer yourself',
    username_not_found: 'Username not found',
    reset_password: 'Reset Password',
    new_password: 'New Password',
    confirm_new_password: 'Confirm New Password',
    password_reset_success: 'Password reset successfully',
    password_reset_error: 'Error resetting password',
    passwords_dont_match: 'Passwords don\'t match',
    password_too_weak: 'Password must be at least 6 characters',
    invalid_reset_link: 'Invalid or expired reset link',
    request_new_reset_link: 'Request new link',
    enter_new_password: 'Enter your new password',
    forgot_password: 'Forgot Password',
    forgot_password_description: 'Enter your email address and we\'ll send you a link to reset your password',
    reset_email_sent_description: 'An email has been sent with instructions to reset your password',
    check_email_for_reset_link: 'Check your email for the reset link',
    back_to_login: 'Back to login',
    send_reset_link: 'Send reset link',
    most_popular: 'Most Popular',
    per_month: '/month',
    current_plan: 'Current Plan',
    upgrade: 'Upgrade',
    downgrade: 'Downgrade',
    switch_plan: 'Switch Plan',
    subscribe_to_plan: 'Subscribe Now',
    support_them: 'Enter the username of the person who referred you to support them',
    all_plans_include: 'All plans include access to exam papers, corrections, and regular content updates. No payment required - instant activation!',
    processing: 'Processing...',
    active: 'Active',
    
    // Payment Processing
    payment_processing: 'Processing Payment',
    payment_processing_desc: 'Please complete the payment on your mobile device.',
    payment_success: 'Payment Successful!',
    payment_success_desc: 'Your subscription has been activated successfully.',
    payment_failed: 'Payment Failed',
    payment_failed_desc: 'Your payment could not be processed. Please try again.',
    check: 'Check',
    of: 'of',
    cancel_go_back: 'Cancel and Go Back',
    go_to_subscriptions: 'Go to Subscriptions',
    go_to_exams: 'Go to Exams',
    try_again: 'Try Again',
    back_to_plans: 'Back to Plans',
    check_phone_payment: 'Check your phone for the payment prompt',
    what_to_do_next: 'What to do next:',
    check_phone_notification: 'Check your phone for a payment notification',
    enter_pin: 'Enter your mobile money PIN when prompted',
    confirm_amount: 'Confirm the payment amount',
    wait_confirmation: 'Wait for confirmation',
    
    // Evaluation Mode
    evaluation_results: 'Evaluation Results',
    correct_answers: 'Correct answers',
    score: 'Score',
    retry_evaluation: 'Retry Evaluation',
    submit_evaluation: 'Submit Evaluation',
    answer_at_least_one: 'Answer at least one question to submit',
    evaluation_submitted: 'Evaluation Submitted',
    your_score: 'Your score',
    
    // Transaction History
    transaction_history: 'Transaction History',
    date: 'Date',
    amount: 'Amount',
    provider: 'Provider',
    reference: 'Reference',
    
    // Exam Manager
    create_exam: 'Create Exam',
    edit_exam: 'Edit Exam',
    exam_details: 'Exam Details',
    exam_title: 'Exam Title',
    year: 'Year',
    exam_type: 'Exam Type',
    class: 'Class',
    select_class: 'Select a class',
    period: 'Period',
    language: 'Language',
    duration: 'Duration (minutes)',
    enter_tags: 'Enter tags (comma separated)',
    content_editor: 'Content Editor',
    form_builder: 'Form Builder',
    json_editor: 'JSON Editor',
    pdf_upload: 'PDF Upload',
    upload_pdf: 'Upload PDF File',
    choose_file: 'Choose File',
    no_file_chosen: 'No file chosen',
    upload: 'Upload',
    copy_template: 'Copy Template',
    validate_json: 'Validate JSON',
    json_valid: 'JSON is valid',
    json_invalid: 'JSON is invalid',
    preview: 'Preview',
    save_draft: 'Save Draft',
    publish_exam: 'Publish Exam',
    publish_and_create_another: 'Publish & Create Another',
    click_to_edit: 'Click on any text to edit',
    pdf_preview: 'PDF Preview',
    add_content_below: 'Add exam content below to see the preview',

    // About Page
    about: 'About',
    about_title: 'About Yimaprof',
    about_description: 'Yimaprof is an educational platform dedicated to academic excellence in Africa. We make education accessible by providing quality exam resources to students in both Francophone and Anglophone systems.',
    our_mission: 'Our Mission',
    mission_description: 'Our mission is to democratize access to quality educational resources across Africa. We believe every student deserves the best opportunities to succeed in their exams and reach their full academic potential.',
    our_values: 'Our Values',
    excellence: 'Excellence',
    excellence_desc: 'We are committed to providing the highest quality resources',
    accessibility_desc: 'Making education accessible to all students',
    diversity_desc: 'Celebrating the diversity of African educational systems',
    innovation: 'Innovation',
    innovation_desc: 'Using technology to transform learning',
    our_story: 'Our Story',
    story_paragraph_1: 'Yimaprof was founded with a simple yet powerful vision: to give every African student access to the resources they need to succeed. We started by recognizing the challenge many students face in accessing past exam papers and study materials.',
    story_paragraph_2: 'Since our launch, we have grown to become the go-to platform for exam papers across Francophone and Anglophone educational systems. Our collection has expanded to include thousands of papers covering multiple years, levels, and subjects.',
    story_paragraph_3: 'Today, Yimaprof serves thousands of students across Africa, helping them prepare effectively for their examinations. We continue to innovate and expand our offerings to better serve the educational community.',
    join_us_description: 'Join our growing community of students and start your journey to academic success today.',

    // Contact Page
    contact_us: 'Contact Us',
    contact_description: 'Have questions or need assistance? Our team is here to help. Reach out to us and we\'ll get back to you as soon as possible.',
    send_message: 'Send Message',
    first_name: 'First Name',
    last_name: 'Last Name',
    contact_info: 'Contact Information',
    hours: 'Hours',
    support_hours: 'Monday - Friday: 8:00 AM - 6:00 PM (WAT)',
    faq_title: 'Frequently Asked Questions',
    faq_1_question: 'How can I access exams?',
    faq_1_answer: 'Simply create a free account and browse our exam library. Some exams require a premium subscription.',
    faq_2_question: 'Are solutions available?',
    faq_2_answer: 'Yes, many exams include detailed solutions and marking schemes to help you understand the answers.',
    faq_3_question: 'Can I download exams?',
    faq_3_answer: 'Yes, subscribers can download exams for offline study at any time.',

    // Privacy Page
    privacy_intro: 'Yimaprof ("us", "we", or "our") operates the yimaprof.com website and Yimaprof mobile application (hereinafter referred to as the "Service"). This page informs you of our policies regarding the collection, use, and disclosure of personal data when you use our Service.',
    privacy_data_collection_title: 'Data Collection and Use',
    privacy_data_collection: 'We collect several different types of information for various purposes to provide and improve our Service to you.',
    privacy_types_title: 'Types of Data Collected',
    privacy_personal_data: 'While using our Service, we may ask you to provide us with certain personally identifiable information that can be used to contact or identify you ("Personal Data"). Personally identifiable information may include, but is not limited to: email address, first name and last name, phone number, cookies and usage data.',
    privacy_usage_data: 'We may also collect information on how the Service is accessed and used ("Usage Data"). This Usage Data may include information such as your computer\'s Internet Protocol address (e.g. IP address), browser type, browser version, the pages of our Service that you visit, the time and date of your visit, the time spent on those pages, unique device identifiers and other diagnostic data.',
    privacy_use_title: 'Use of Data',
    privacy_use: 'Yimaprof uses the collected data for various purposes: to provide and maintain our Service, to notify you about changes to our Service, to allow you to participate in interactive features of our Service when you choose to do so, to provide customer support, to gather analysis or valuable information so that we can improve our Service, to monitor the usage of our Service, to detect, prevent and address technical issues.',
    privacy_data_sharing_title: 'Data Sharing',
    privacy_data_sharing: 'We do not sell, trade, or rent your personal information to third parties. We may share aggregated demographic information not linked to any personal information with our business partners and advertisers.',
    privacy_security_title: 'Data Security',
    privacy_security: 'The security of your data is important to us, but remember that no method of transmission over the Internet, or method of electronic storage is 100% secure. While we strive to use commercially acceptable means to protect your Personal Data, we cannot guarantee its absolute security.',
    privacy_rights_title: 'Your Rights',
    privacy_rights: 'You have the right to access, update or delete the information we have on you. You can also contact us to exercise these rights.',
    privacy_cookies_title: 'Cookies',
    privacy_cookies: 'We use cookies and similar tracking technologies to track the activity on our Service and we hold certain information. You can instruct your browser to refuse all cookies or to indicate when a cookie is being sent.',
    privacy_changes_title: 'Changes to This Policy',
    privacy_changes: 'We may update our Privacy Policy from time to time. We will notify you of any changes by posting the new Privacy Policy on this page and updating the "last updated" date.',
    privacy_contact_title: 'Contact Us',
    privacy_contact: 'If you have any questions about this Privacy Policy, please contact us at privacy@yima.cm',

    // Terms Page
    terms_last_updated: 'Last updated: January 2025',
    terms_acceptance_title: 'Acceptance of Terms',
    terms_acceptance: 'By accessing and using Yimaprof, you agree to be bound by these Terms of Service. If you do not agree to these terms, please do not use our Service.',
    terms_description_title: 'Service Description',
    terms_description: 'Yimaprof provides an online platform for accessing exam papers, study materials, and related educational resources for Francophone and Anglophone educational systems in Africa.',
    terms_user_accounts_title: 'User Accounts',
    terms_user_accounts: 'To access certain features of the Service, you will need to create an account. You agree to:',
    terms_account_accuracy: 'Provide accurate, current, and complete information',
    terms_account_security: 'Maintain the security of your password and account',
    terms_account_responsibility: 'Accept responsibility for all activities that occur under your account',
    terms_account_age: 'Be at least 13 years old or have parental consent',
    terms_use_rules_title: 'Usage Rules',
    terms_use_rules: 'You agree not to:',
    terms_rule_legal: 'Use the Service for any illegal purposes',
    terms_rule_respect: 'Violate any third-party intellectual property rights',
    terms_rule_no_sharing: 'Share your account with others',
    terms_rule_no_reverse: 'Attempt to reverse engineer the Service',
    terms_rule_no_automated: 'Use automated systems to access the Service',
    terms_intellectual_property_title: 'Intellectual Property',
    terms_intellectual_property: 'All content available on Yimaprof, including exam papers, text, graphics, and code, is protected by copyright laws and belongs to Yimaprof or its licensors.',
    terms_subscriptions_title: 'Subscriptions and Payments',
    terms_subscriptions: 'Certain features require a paid subscription. You agree that:',
    terms_subscription_billing: 'Subscriptions are billed in advance on a recurring basis',
    terms_subscription_renewal: 'Subscriptions automatically renew unless cancelled',
    terms_subscription_cancellation: 'You may cancel at any time',
    terms_subscription_refund: 'Refunds are handled according to our refund policy',
    terms_termination_title: 'Termination',
    terms_termination: 'We reserve the right to suspend or terminate your account if you violate these Terms of Service or for any other reason we deem necessary.',
    terms_disclaimer_title: 'Disclaimer',
    terms_disclaimer: 'The Service is provided "as is" without warranties of any kind. We do not guarantee that the Service will be uninterrupted, secure, or error-free.',
    terms_limitation_title: 'Limitation of Liability',
    terms_limitation: 'Yimaprof shall not be liable for any indirect, incidental, special, consequential or punitive damages resulting from your use of or inability to use the Service.',
    terms_governing_law_title: 'Governing Law',
    terms_governing_law: 'These Terms are governed by the laws of Cameroon. Any disputes will be resolved in the courts of Cameroon.',
    terms_changes_title: 'Changes to Terms',
    terms_changes: 'We may modify these Terms at any time. We will notify you of significant changes via email or a notification on the Service.',
    terms_contact_title: 'Contact',
    terms_contact: 'For any questions about these Terms, please contact us at:',
    
    // Notifications - detailed
    unreadNotifications: 'unread',
    noNotifications: 'No notifications',
    noNotificationsDesc: 'You don\'t have any notifications yet',
    viewAllNotifications: 'View all notifications',
    markAllRead: 'Mark all as read',
    allTypes: 'All Types',
    subscriptionExpiry: 'Subscription Expiry',
    paymentConfirmed: 'Payment Confirmed',
    adminMessage: 'Admin Message',
    accountActivity: 'Account Activity',
    allNotifications: 'All',
    readNotifications: 'Read',
    loadMore: 'Load more',
    
    // Admin Notification Composer
    composeNotification: 'Compose Notification',
    composeNotificationDesc: 'Create and send notifications to users',
    notificationTitle: 'Notification title',
    notificationMessage: 'Notification message',
    recipientFilters: 'Recipient Filters',
    sendToAllUsers: 'Send to all users',
    subscriptionPlans: 'Subscription Plans',
    subscriptionStatus: 'Subscription Status',
    classLevels: 'Class Levels',
    activeStatus: 'Active',
    pendingStatus: 'Pending',
    expiredStatus: 'Expired',
    canceledStatus: 'Canceled',
    lowPriority: 'Low',
    normalPriority: 'Normal',
    highPriority: 'High',
    actionUrl: 'Action URL',
    optional: 'optional',
    previewNotification: 'Preview',
    sendNotification: 'Send Notification',
    sending: 'Sending',
    notificationPreview: 'Notification Preview',
    previewDesc: 'This is how your notification will look',
    notificationSent: 'Notification sent to',
    recipients: 'recipients',
    notificationSendFailed: 'Failed to send notification',
    noRecipientsFound: 'No recipients found with selected filters',
    fillRequiredFields: 'Please fill all required fields',
    allUsers: 'All users',
    
    // Write to Us / Feedback
    write_to_us: 'Write to Us',
    feedback_intro: 'We value your opinion! Use this form to share your feedback, suggestions, requests, or reviews. Your thoughts help us improve and serve you better.',
    share_feedback: 'Share Your Feedback',
    feedback_form_desc: 'Let us know what you think. Your feedback is important to us.',
    your_feedback: 'Your Feedback',
    feedback_placeholder: 'Share your thoughts, suggestions, or feedback here...',
    send_feedback: 'Send Feedback',
    character_count: '{count} / 1000 characters',
    feedback_success_title: 'Thank you for your feedback!',
    feedback_success: 'Our team will review it soon.',
    feedback_error_title: 'Error',
    feedback_error: 'Failed to send feedback. Please try again.',
    login_to_feedback: 'Please log in to send us your feedback.',
    feedback_privacy_note: 'Your feedback is confidential and helps us improve our services.',
    login_required: 'Login Required',
    
    // Admin - Feedback Management
    user_feedback: 'User Feedback',
    manage_user_feedback: 'View and manage user feedback submissions',
    feedback_status_new: 'New',
    feedback_status_reviewed: 'Reviewed',
    feedback_status_replied: 'Replied',
    view_details: 'View Details',
    feedback_details: 'Feedback Details',
    view_full_feedback: 'View the complete feedback and update status',
    feedback_content: 'Feedback Content',
    update_status: 'Update Status',
    status_updated: 'Status Updated',
    feedback_status_updated: 'Feedback status updated successfully',
    failed_to_load_feedback: 'Failed to load feedback',
    failed_to_update_status: 'Failed to update status',
    unknown_user: 'Unknown User',
    no_email: 'No email',
    all: 'All',
    refresh: 'Refresh',
    
    // Dashboard
    profilePhoto: 'Profile Photo',
    managePersonalInfo: 'Manage your personal information',
    editProfile: 'Edit Profile',
    saveChanges: 'Save Changes',
    firstName: 'First Name',
    lastName: 'Last Name',
    uploadPhoto: 'Upload Photo',
    uploading: 'Uploading...',
    saving: 'Saving...',
    profileUpdated: 'Profile updated successfully',
    profileError: 'Error updating profile',
    statistics: 'Statistics',
    learningProgress: 'Your learning progress',
    examsCompleted: 'Exams Completed',
    totalPoints: 'Total Points',
    averageScore: 'Average Score',
    studyStreak: 'Study Streak (days)',
    currentPlan: 'Your current plan and status',
    expiresOn: 'Expires On',
    free: 'Free',
    managePlan: 'Manage Plan',
    recentExams: 'Recent Exams',
    latestPractice: 'Your latest practice sessions',
    noExams: 'No recent exams',
    viewAll: 'View All',
    
    // Settings
    settingsTitle: 'Settings',
    manageAccountSettings: 'Manage your account settings and preferences',
    accountSettings: 'Manage your account information',
    selectClassLevel: 'Select class level',
    preferredLanguage: 'Preferred Language for Content',
    notificationPreferences: 'Manage your notification preferences',
    receiveEmailNotif: 'Receive email notifications',
    emailSubscriptionExpiry: 'Subscription Expiry',
    emailPaymentConfirmed: 'Payment Confirmation',
    emailAdminMessages: 'Admin Messages',
    inAppNotifications: 'In-App Notifications',
    inAppSubscriptionExpiry: 'Subscription Expiry',
    inAppPaymentConfirmed: 'Payment Confirmation',
    inAppAdminMessages: 'Admin Messages',
    inAppAccountActivity: 'Account Activity',
    interfaceLanguage: 'Interface Language',
    chooseInterfaceLanguage: 'Choose your preferred interface language',
    accountSecurity: 'Manage your account security',
    changePassword: 'Change Password',
    twoFactorAuth: 'Two-Factor Authentication',
    extraSecurity: 'Add an extra layer of security',
    settingsSaved: 'Settings saved successfully',
    settingsError: 'Error saving settings',
    
    // Exam Manager
    examSchool: 'School/Establishment',
    examAddNewSchool: 'Add new school',
    examSubject: 'Subject',
    examAddNewSubject: 'Add new subject',
    examType: 'Exam Type',
    examDuringYear: 'During the Year Evaluation',
    examEndTerm: 'End of Term Evaluation',
    examAcademicYear: 'Academic Year',
    examAddNewYear: 'Add new year',
    examPeriod: 'Period/Semester',
    examDuration: 'Duration',
    examAddCustomDuration: 'Add custom duration',
    examSelectSchool: 'Select school',
    examSelectSubject: 'Select subject',
    examSelectExamType: 'Select exam type',
    examSelectYear: 'Select year',
    examSelectPeriod: 'Select period',
    examSelectDuration: 'Select duration',
    examEnglishName: 'English Name',
    examFrenchName: 'French Name',
    examSchoolName: 'School Name',
    examYearFormat: 'Year Format (e.g., 2024-2025)',
    examDurationMinutes: 'Duration (minutes)',
    examAddingSchool: 'Add New School',
    examAddingSubject: 'Add New Subject',
    examAddingYear: 'Add New Academic Year',
    examAddingDuration: 'Add New Duration',
    examSuccessSchool: 'School added successfully',
    examSuccessSubject: 'Subject added successfully',
    examSuccessYear: 'Academic year added successfully',
    examSuccessDuration: 'Duration added successfully',
    examErrorAdding: 'Failed to add item',
    
    // Admin Exams Page
    exam_management: 'Exam Management',
    search_exams: 'Search exams...',
    language_filter: 'Language',
    year_filter: 'Year',
    all_years: 'All Years',
    subject_filter: 'Subject',
    all_subjects: 'All Subjects',
    class_filter: 'Class',
    all_classes: 'All Classes',
    school_filter: 'School',
    all_schools: 'All Schools',
    no_school_set: 'No School Set',
    status_filter: 'Status',
    all_status: 'All Status',
    published: 'Published',
    draft: 'Draft',
    clear_filters: 'Clear Filters',
    please_sign_in_page: 'Please sign in to access this page.',
    back_to_admin: 'Back to Admin',
    filters: 'Filters',
    add_exam: 'Add Exam',
    hide_filters: 'Hide',
    no_exams_found: 'No exams found matching your criteria',
    previous: 'Previous',
    next: 'Next',
    showing_exams: 'Showing',
    of_exams: 'of',
    
    // Footer
    about_yima: 'Yimaprof is an educational platform dedicated to academic excellence in Africa. We make education accessible by providing quality exam resources.',
    platform: 'Platform',
    company: 'Company',
    stay_updated: 'Stay Updated',
    newsletter_desc: 'Subscribe to our newsletter to receive the latest updates and new exams.',
    enter_email: 'Enter your email',
    rights_reserved: 'All rights reserved.',
  },
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [language, setLanguage] = useState<'fr' | 'en'>('fr');

  useEffect(() => {
    const storedLang = localStorage.getItem('language') as 'fr' | 'en' | null;
    if (storedLang) {
      setLanguage(storedLang);
    }
  }, []);

  // Listen for toggle-language custom event
  useEffect(() => {
    const handleToggleLanguage = () => {
      setLanguage(prev => {
        const newLang = prev === 'fr' ? 'en' : 'fr';
        localStorage.setItem('language', newLang);
        return newLang;
      });
    };

    window.addEventListener('toggle-language', handleToggleLanguage);
    return () => window.removeEventListener('toggle-language', handleToggleLanguage);
  }, []);

  const handleSetLanguage = (lang: 'fr' | 'en') => {
    setLanguage(lang);
    localStorage.setItem('language', lang);
  };

  const t = (key: string): string => {
    return translations[language][key as keyof typeof translations['fr']] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage: handleSetLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}
