import React, { createContext, useContext, useState, useEffect } from 'react';

interface LanguageContextType {
  language: 'fr' | 'en';
  setLanguage: (lang: 'fr' | 'en') => void;
  t: (key: string) => string;
}

const translations = {
  fr: {
    navigation: 'Navigation',
    homepage: 'Page d\'accueil',
    features: 'Fonctionnalités',
    pricing: 'Tarification',
    contact: 'Contact',
    login: 'Se connecter',
    logout: 'Déconnexion',
    register: 'S\'inscrire',
    dashboard: 'Tableau de bord',
    profile: 'Profil',
    settings: 'Paramètres',
    welcome: 'Bienvenue',
    description: 'Description',
    get_started: 'Commencer',
    about_us: 'À propos de nous',
    our_team: 'Notre équipe',
    services: 'Services',
    testimonials: 'Témoignages',
    faq: 'FAQ',
    blog: 'Blog',
    news: 'Actualités',
    careers: 'Carrières',
    terms: 'Conditions d\'utilisation',
    privacy: 'Politique de confidentialité',
    cookie: 'Politique de cookies',
    support: 'Support',
    help: 'Aide',
    documentation: 'Documentation',
    api: 'API',
    community: 'Communauté',
    forum: 'Forum',
    chat: 'Chat',
    email: 'Courriel',
    phone: 'Téléphone',
    address: 'Adresse',
    copyright: 'Droits d\'auteur',
    all_rights_reserved: 'Tous droits réservés',
    home: 'Accueil',
    exams: 'Examens',
    practice: 'Pratique',
    quizzes: 'Quiz',
    lessons: 'Leçons',
    courses: 'Cours',
    curriculum: 'Programme',
    teachers: 'Professeurs',
    students: 'Étudiants',
    grades: 'Notes',
    calendar: 'Calendrier',
    messages: 'Messages',
    notifications: 'Notifications',
    tasks: 'Tâches',
    files: 'Fichiers',
    resources: 'Ressources',
    tools: 'Outils',
    reports: 'Rapports',
    analytics: 'Analytique',
    performance: 'Performance',
    progress: 'Progrès',
    results: 'Résultats',
    feedback: 'Commentaires',
    survey: 'Sondage',
    poll: 'Vote',
    events: 'Événements',
    webinars: 'Webinaires',
    workshops: 'Ateliers',
    seminars: 'Séminaires',
    conferences: 'Conférences',
    activities: 'Activités',
    achievements: 'Réalisations',
    awards: 'Prix',
    certificates: 'Certificats',
    partners: 'Partenaires',
    sponsors: 'Commanditaires',
    investors: 'Investisseurs',
    clients: 'Clients',
    projects: 'Projets',
    products: 'Produits',
    solutions: 'Solutions',
    services_offered: 'Services offerts',
    case_studies: 'Études de cas',
    success_stories: 'Histoires de succès',
    mission: 'Mission',
    vision: 'Vision',
    values: 'Valeurs',
    team: 'Équipe',
    leadership: 'Direction',
    board_of_directors: 'Conseil d\'administration',
    advisors: 'Conseillers',
    careers_at: 'Carrières chez',
    open_positions: 'Postes ouverts',
    apply_now: 'Postuler maintenant',
    internships: 'Stages',
    volunteering: 'Bénévolat',
    diversity: 'Diversité',
    inclusion: 'Inclusion',
    equity: 'Équité',
    accessibility: 'Accessibilité',
    sustainability: 'Durabilité',
    impact: 'Impact',
    donate: 'Faire un don',
    volunteer: 'Bénévole',
    join_us: 'Rejoignez-nous',
    subscribe: 'S\'abonner',
    follow_us: 'Suivez-nous',
    share: 'Partager',
    like: 'J\'aime',
    comment: 'Commenter',
    read_more: 'Lire la suite',
    view_all: 'Voir tout',
    latest_news: 'Dernières nouvelles',
    featured_articles: 'Articles en vedette',
    popular_topics: 'Sujets populaires',
    categories: 'Catégories',
    tags: 'Mots-clés',
    archive: 'Archive',
    search: 'Rechercher',
    no_results_found: 'Aucun résultat trouvé',
    error_404: 'Erreur 404',
    page_not_found: 'Page non trouvée',
    back_to_home: 'Retour à l\'accueil',
    loading: 'Chargement',
    please_wait: 'Veuillez patienter',
    submit: 'Soumettre',
    send: 'Envoyer',
    reset: 'Réinitialiser',
    update: 'Mettre à jour',
    delete: 'Supprimer',
    cancel: 'Annuler',
    save: 'Enregistrer',
    edit: 'Modifier',
    add_new: 'Ajouter',
    create: 'Créer',
    manage: 'Gérer',
    view: 'Voir',
    details: 'Détails',
    options: 'Options',
    actions: 'Actions',
    confirm: 'Confirmer',
    are_you_sure: 'Êtes-vous sûr ?',
    yes: 'Oui',
    no: 'Non',
    success: 'Succès',
    error: 'Erreur',
    warning: 'Avertissement',
    information: 'Information',
    required_fields: 'Champs obligatoires',
    invalid_email: 'Adresse e-mail invalide',
    password_mismatch: 'Les mots de passe ne correspondent pas',
    password_length: 'Le mot de passe doit contenir au moins 8 caractères',
    username_exists: 'Ce nom d\'utilisateur existe déjà',
    email_exists: 'Cette adresse e-mail existe déjà',
    login_failed: 'Échec de la connexion',
    registration_successful: 'Inscription réussie',
    password_reset_sent: 'Un e-mail de réinitialisation du mot de passe a été envoyé',
    password_reset_successful: 'Réinitialisation du mot de passe réussie',
    profile_updated: 'Profil mis à jour',
    data_saved: 'Données enregistrées',
    data_deleted: 'Données supprimées',
    item_added: 'Élément ajouté',
    item_updated: 'Élément mis à jour',
    item_deleted: 'Élément supprimé',
    message_sent: 'Message envoyé',
    subscription_successful: 'Abonnement réussi',
    payment_successful: 'Paiement réussi',
    order_placed: 'Commande passée',
    download_started: 'Téléchargement démarré',
    file_uploaded: 'Fichier téléchargé',
    task_completed: 'Tâche terminée',
    event_created: 'Événement créé',
    award_received: 'Prix reçu',
    certificate_earned: 'Certificat obtenu',
    thank_you: 'Merci',
    congratulations: 'Félicitations',
    welcome_aboard: 'Bienvenue à bord',
    get_in_touch: 'Contactez-nous',
    send_us_a_message: 'Envoyez-nous un message',
    your_name: 'Votre nom',
    your_email: 'Votre e-mail',
    subject: 'Sujet',
    message: 'Message',
    i_agree_to_the: 'J\'accepte les',
    and: 'et',
    privacy_policy: 'politique de confidentialité',
    terms_of_service: 'conditions d\'utilisation',
    sign_up_for_our_newsletter: 'Inscrivez-vous à notre newsletter',
    enter_your_email: 'Entrez votre e-mail',
    subscribe_now: 'Abonnez-vous maintenant',
    stay_up_to_date: 'Restez à jour',
    never_miss_an_update: 'Ne manquez jamais une mise à jour',
    we_respect_your_privacy: 'Nous respectons votre vie privée',
    unsubscribe_at_any_time: 'Désabonnez-vous à tout moment',
    learn_more: 'En savoir plus',
    explore: 'Explorer',
    discover: 'Découvrir',
    browse: 'Parcourir',
    find_out_more: 'Découvrez-en plus',
    start_learning: 'Commencer à apprendre',
    improve_your_skills: 'Améliorez vos compétences',
    become_an_expert: 'Devenez un expert',
    unlock_your_potential: 'Libérez votre potentiel',
    achieve_your_goals: 'Atteignez vos objectifs',
    transform_your_life: 'Transformez votre vie',
    invest_in_yourself: 'Investissez en vous-même',
    join_our_community: 'Rejoignez notre communauté',
    connect_with_experts: 'Connectez-vous avec des experts',
    share_your_knowledge: 'Partagez vos connaissances',
    get_inspired: 'Inspirez-vous',
    stay_motivated: 'Restez motivé',
    celebrate_success: 'Célébrez le succès',
    make_a_difference: 'Faites la différence',
    create_a_better_future: 'Créez un avenir meilleur',
    together_we_can: 'Ensemble, nous pouvons',
    making_education_accessible: 'Rendre l\'éducation accessible',
    empowering_learners_worldwide: 'Autonomiser les apprenants du monde entier',
    building_a_brighter_tomorrow: 'Construire un avenir meilleur',
    education_for_all: 'L\'éducation pour tous',
    a_world_of_knowledge: 'Un monde de connaissances',
    your_path_to_success: 'Votre chemin vers le succès',
    the_future_of_learning: 'L\'avenir de l\'apprentissage',
    unlocking_human_potential: 'Libérer le potentiel humain',
    transforming_lives_through_education: 'Transformer des vies grâce à l\'éducation',
    creating_opportunities_for_everyone: 'Créer des opportunités pour tous',
    investing_in_the_next_generation: 'Investir dans la prochaine génération',
    inspiring_a_love_of_learning: 'Inspirer l\'amour de l\'apprentissage',
    making_a_positive_impact: 'Avoir un impact positif',
    building_a_global_community: 'Construire une communauté mondiale',
    connecting_people_through_education: 'Connecter les gens grâce à l\'éducation',
    empowering_individuals_and_communities: 'Autonomiser les individus et les communautés',
    creating_a_more_equitable_world: 'Créer un monde plus équitable',
    working_together_for_a_better_future: 'Travailler ensemble pour un avenir meilleur',
    join_us_on_this_journey: 'Rejoignez-nous dans ce voyage',
    together_we_can_make_a_difference: 'Ensemble, nous pouvons faire la différence',
    thank_you_for_being_part_of_our_community: 'Merci de faire partie de notre communauté',
    we_appreciate_your_support: 'Nous apprécions votre soutien',
    together_we_are_making_a_difference: 'Ensemble, nous faisons la différence',
    welcome_to_our_platform: 'Bienvenue sur notre plateforme',
    we_are_excited_to_have_you_with_us: 'Nous sommes ravis de vous avoir parmi nous',
    let_s_start_learning_together: 'Commençons à apprendre ensemble',
    we_are_here_to_help_you_succeed: 'Nous sommes là pour vous aider à réussir',
    thank_you_for_choosing_us: 'Merci de nous avoir choisis',
    we_look_forward_to_helping_you_achieve_your_goals: 'Nous sommes impatients de vous aider à atteindre vos objectifs',
    together_we_can_achieve_great_things: 'Ensemble, nous pouvons réaliser de grandes choses',
    thank_you_for_your_trust: 'Merci de votre confiance',
    we_are_committed_to_your_success: 'Nous nous engageons à votre succès',
    together_we_will_build_a_brighter_future: 'Ensemble, nous construirons un avenir meilleur',

    // Admin Page
    admin_dashboard: 'Tableau de bord administrateur',
    platform_management: 'Gestion de la plateforme et analytiques',
    admin_access: 'Accès administrateur',
    overview: 'Vue d\'ensemble',
    users: 'Utilisateurs',
    classes: 'Classes',
    plans: 'Plans',
    subscriptions: 'Abonnements',
    transactions: 'Transactions',
    platform_overview: 'Aperçu de la plateforme',
    total_revenue: 'Revenu total',
    updated_realtime: 'Mis à jour en temps réel',
    active_users: 'Utilisateurs actifs',
    last_30_days: '30 derniers jours',
    platform_health: 'Santé de la plateforme',
    excellent: 'Excellent',
    quick_navigation: 'Navigation rapide',
    quick_nav_desc: 'Utilisez le menu de navigation pour gérer différentes sections :',
    users_manage_desc: 'Gérer les comptes utilisateurs et les rôles',
    exams_manage_desc: 'Opérations CRUD pour les sujets d\'examen',
    classes_manage_desc: 'Gérer les classes éducatives',
    plans_manage_desc: 'Gestion des plans d\'abonnement',
    subscriptions_manage_desc: 'Voir les abonnements actifs',
    transactions_manage_desc: 'Historique des transactions financières',
    please_sign_in_admin: 'Veuillez vous connecter pour accéder au panneau d\'administration',
    loading_admin_panel: 'Chargement du panneau d\'administration...',
    access_denied: 'Accès refusé',
    no_admin_privileges: 'Vous n\'avez pas les privilèges d\'administrateur pour accéder à cette page.',
    access_denied_desc: 'Vous n\'avez pas les privilèges d\'administrateur',
    
    // User Management
    user_management: 'Gestion des utilisateurs',
    joined: 'Inscrit le',
    remove_admin: 'Retirer Admin',
    make_admin: 'Rendre Admin',
    
    // Class Management
    class_management: 'Gestion des classes',
    add_class: 'Ajouter une classe',
    edit_class: 'Modifier la classe',
    add_new_class: 'Ajouter une nouvelle classe',
    display_name: 'Nom d\'affichage',
    internal_name: 'Nom interne',
    delete_confirm_class: 'Êtes-vous sûr de vouloir supprimer cette classe ? Cela affectera tous les examens associés.',
    created: 'Créé',
    
    // Subscription Plan Management
    subscription_plan_management: 'Gestion des plans d\'abonnement',
    add_plan: 'Ajouter un plan',
    edit_subscription_plan: 'Modifier le plan d\'abonnement',
    add_new_subscription_plan: 'Ajouter un nouveau plan d\'abonnement',
    plan_name: 'Nom du plan',
    duration_days: 'Durée (jours)',
    max_downloads: 'Téléchargements max',
    max_downloads_hint: '999999 pour illimité',
    features_placeholder: 'Accès aux examens du curriculum français\nVoir les corrections et solutions\nTélécharger les sujets d\'examen',
    deactivate: 'Désactiver',
    activate: 'Activer',
    unlimited: 'Illimité',
    delete_confirm_plan: 'Êtes-vous sûr de vouloir supprimer ce plan d\'abonnement ? Cela affectera tous les abonnements associés.',
    
    // Active Subscriptions
    active_subscriptions: 'Abonnements actifs',
    started: 'Commencé',
    expires: 'Expire',
    auto_renew: 'Renouvellement auto',
    days_left: 'jours restants',
    cancel_subscription: 'Annuler',
    cancel_confirm_subscription: 'Êtes-vous sûr de vouloir annuler cet abonnement ?',
    
    // Transaction History
    transaction_history: 'Historique des transactions',
    date: 'Date',
    amount: 'Montant',
    provider: 'Fournisseur',
    reference: 'Référence',
  },
  en: {
    navigation: 'Navigation',
    homepage: 'Homepage',
    features: 'Features',
    pricing: 'Pricing',
    contact: 'Contact',
    login: 'Login',
    logout: 'Logout',
    register: 'Register',
    dashboard: 'Dashboard',
    profile: 'Profile',
    settings: 'Settings',
    welcome: 'Welcome',
    description: 'Description',
    get_started: 'Get Started',
    about_us: 'About Us',
    our_team: 'Our Team',
    services: 'Services',
    testimonials: 'Testimonials',
    faq: 'FAQ',
    blog: 'Blog',
    news: 'News',
    careers: 'Careers',
    terms: 'Terms of Use',
    privacy: 'Privacy Policy',
    cookie: 'Cookie Policy',
    support: 'Support',
    help: 'Help',
    documentation: 'Documentation',
    api: 'API',
    community: 'Community',
    forum: 'Forum',
    chat: 'Chat',
    email: 'Email',
    phone: 'Phone',
    address: 'Address',
    copyright: 'Copyright',
    all_rights_reserved: 'All Rights Reserved',
    home: 'Home',
    exams: 'Exams',
    practice: 'Practice',
    quizzes: 'Quizzes',
    lessons: 'Lessons',
    courses: 'Courses',
    curriculum: 'Curriculum',
    teachers: 'Teachers',
    students: 'Students',
    grades: 'Grades',
    calendar: 'Calendar',
    messages: 'Messages',
    notifications: 'Notifications',
    tasks: 'Tasks',
    files: 'Files',
    resources: 'Resources',
    tools: 'Tools',
    reports: 'Reports',
    analytics: 'Analytics',
    performance: 'Performance',
    progress: 'Progress',
    results: 'Results',
    feedback: 'Feedback',
    survey: 'Survey',
    poll: 'Poll',
    events: 'Events',
    webinars: 'Webinars',
    workshops: 'Workshops',
    seminars: 'Seminars',
    conferences: 'Conferences',
    activities: 'Activities',
    achievements: 'Achievements',
    awards: 'Awards',
    certificates: 'Certificates',
    partners: 'Partners',
    sponsors: 'Sponsors',
    investors: 'Investors',
    clients: 'Clients',
    projects: 'Projects',
    products: 'Products',
    solutions: 'Solutions',
    services_offered: 'Services Offered',
    case_studies: 'Case Studies',
    success_stories: 'Success Stories',
    mission: 'Mission',
    vision: 'Vision',
    values: 'Values',
    team: 'Team',
    leadership: 'Leadership',
    board_of_directors: 'Board of Directors',
    advisors: 'Advisors',
    careers_at: 'Careers at',
    open_positions: 'Open Positions',
    apply_now: 'Apply Now',
    internships: 'Internships',
    volunteering: 'Volunteering',
    diversity: 'Diversity',
    inclusion: 'Inclusion',
    equity: 'Equity',
    accessibility: 'Accessibility',
    sustainability: 'Sustainability',
    impact: 'Impact',
    donate: 'Donate',
    volunteer: 'Volunteer',
    join_us: 'Join Us',
    subscribe: 'Subscribe',
    follow_us: 'Follow Us',
    share: 'Share',
    like: 'Like',
    comment: 'Comment',
    read_more: 'Read More',
    view_all: 'View All',
    latest_news: 'Latest News',
    featured_articles: 'Featured Articles',
    popular_topics: 'Popular Topics',
    categories: 'Categories',
    tags: 'Tags',
    archive: 'Archive',
    search: 'Search',
    no_results_found: 'No Results Found',
    error_404: 'Error 404',
    page_not_found: 'Page Not Found',
    back_to_home: 'Back to Home',
    loading: 'Loading',
    please_wait: 'Please Wait',
    submit: 'Submit',
    send: 'Send',
    reset: 'Reset',
    update: 'Update',
    delete: 'Delete',
    cancel: 'Cancel',
    save: 'Save',
    edit: 'Edit',
    add_new: 'Add New',
    create: 'Create',
    manage: 'Manage',
    view: 'View',
    details: 'Details',
    options: 'Options',
    actions: 'Actions',
    confirm: 'Confirm',
    are_you_sure: 'Are you sure?',
    yes: 'Yes',
    no: 'No',
    success: 'Success',
    error: 'Error',
    warning: 'Warning',
    information: 'Information',
    required_fields: 'Required Fields',
    invalid_email: 'Invalid Email',
    password_mismatch: 'Passwords do not match',
    password_length: 'Password must be at least 8 characters',
    username_exists: 'Username already exists',
    email_exists: 'Email already exists',
    login_failed: 'Login Failed',
    registration_successful: 'Registration Successful',
    password_reset_sent: 'Password reset email sent',
    password_reset_successful: 'Password reset successful',
    profile_updated: 'Profile Updated',
    data_saved: 'Data Saved',
    data_deleted: 'Data Deleted',
    item_added: 'Item Added',
    item_updated: 'Item Updated',
    item_deleted: 'Item Deleted',
    message_sent: 'Message Sent',
    subscription_successful: 'Subscription Successful',
    payment_successful: 'Payment Successful',
    order_placed: 'Order Placed',
    download_started: 'Download Started',
    file_uploaded: 'File Uploaded',
    task_completed: 'Task Completed',
    event_created: 'Event Created',
    award_received: 'Award Received',
    certificate_earned: 'Certificate Earned',
    thank_you: 'Thank You',
    congratulations: 'Congratulations',
    welcome_aboard: 'Welcome Aboard',
    get_in_touch: 'Get In Touch',
    send_us_a_message: 'Send Us a Message',
    your_name: 'Your Name',
    your_email: 'Your Email',
    subject: 'Subject',
    message: 'Message',
    i_agree_to_the: 'I agree to the',
    and: 'and',
    privacy_policy: 'privacy policy',
    terms_of_service: 'terms of service',
    sign_up_for_our_newsletter: 'Sign Up for Our Newsletter',
    enter_your_email: 'Enter Your Email',
    subscribe_now: 'Subscribe Now',
    stay_up_to_date: 'Stay Up To Date',
    never_miss_an_update: 'Never Miss an Update',
    we_respect_your_privacy: 'We Respect Your Privacy',
    unsubscribe_at_any_time: 'Unsubscribe at Any Time',
    learn_more: 'Learn More',
    explore: 'Explore',
    discover: 'Discover',
    browse: 'Browse',
    find_out_more: 'Find Out More',
    start_learning: 'Start Learning',
    improve_your_skills: 'Improve Your Skills',
    become_an_expert: 'Become an Expert',
    unlock_your_potential: 'Unlock Your Potential',
    achieve_your_goals: 'Achieve Your Goals',
    transform_your_life: 'Transform Your Life',
    invest_in_yourself: 'Invest in Yourself',
    join_our_community: 'Join Our Community',
    connect_with_experts: 'Connect With Experts',
    share_your_knowledge: 'Share Your Knowledge',
    get_inspired: 'Get Inspired',
    stay_motivated: 'Stay Motivated',
    celebrate_success: 'Celebrate Success',
    make_a_difference: 'Make a Difference',
    create_a_better_future: 'Create a Better Future',
    together_we_can: 'Together We Can',
    making_education_accessible: 'Making Education Accessible',
    empowering_learners_worldwide: 'Empowering Learners Worldwide',
    building_a_brighter_tomorrow: 'Building a Brighter Tomorrow',
    education_for_all: 'Education for All',
    a_world_of_knowledge: 'A World of Knowledge',
    your_path_to_success: 'Your Path to Success',
    the_future_of_learning: 'The Future of Learning',
    unlocking_human_potential: 'Unlocking Human Potential',
    transforming_lives_through_education: 'Transforming Lives Through Education',
    creating_opportunities_for_everyone: 'Creating Opportunities for Everyone',
    investing_in_the_next_generation: 'Investing in the Next Generation',
    inspiring_a_love_of_learning: 'Inspiring a Love of Learning',
    making_a_positive_impact: 'Making a Positive Impact',
    building_a_global_community: 'Building a Global Community',
    connecting_people_through_education: 'Connecting People Through Education',
    empowering_individuals_and_communities: 'Empowering Individuals and Communities',
    creating_a_more_equitable_world: 'Creating a More Equitable World',
    working_together_for_a_better_future: 'Working Together for a Better Future',
    join_us_on_this_journey: 'Join Us on This Journey',
    together_we_can_make_a_difference: 'Together We Can Make a Difference',
    thank_you_for_being_part_of_our_community: 'Thank You for Being Part of Our Community',
    we_appreciate_your_support: 'We Appreciate Your Support',
    together_we_are_making_a_difference: 'Together We Are Making a Difference',
    welcome_to_our_platform: 'Welcome to Our Platform',
    we_are_excited_to_have_you_with_us: 'We Are Excited to Have You With Us',
    let_s_start_learning_together: 'Let\'s Start Learning Together',
    we_are_here_to_help_you_succeed: 'We Are Here to Help You Succeed',
    thank_you_for_choosing_us: 'Thank You for Choosing Us',
    we_look_forward_to_helping_you_achieve_your_goals: 'We Look Forward to Helping You Achieve Your Goals',
    together_we_can_achieve_great_things: 'Together We Can Achieve Great Things',
    thank_you_for_your_trust: 'Thank You for Your Trust',
    we_are_committed_to_your_success: 'We Are Committed to Your Success',
    together_we_will_build_a_brighter_future: 'Together We Will Build a Brighter Future',

    // Admin Page
    admin_dashboard: 'Admin Dashboard',
    platform_management: 'Platform management and analytics',
    admin_access: 'Administrator access',
    overview: 'Overview',
    users: 'Users',
    classes: 'Classes',
    plans: 'Plans',
    subscriptions: 'Subscriptions',
    transactions: 'Transactions',
    platform_overview: 'Platform Overview',
    total_revenue: 'Total Revenue',
    updated_realtime: 'Updated in real time',
    active_users: 'Active Users',
    last_30_days: 'Last 30 days',
    platform_health: 'Platform Health',
    excellent: 'Excellent',
    quick_navigation: 'Quick Navigation',
    quick_nav_desc: 'Use the navigation menu to manage different sections:',
    users_manage_desc: 'Manage user accounts and roles',
    exams_manage_desc: 'CRUD operations for exam papers',
    classes_manage_desc: 'Manage educational classes',
    plans_manage_desc: 'Subscription plan management',
    subscriptions_manage_desc: 'View active subscriptions',
    transactions_manage_desc: 'Financial transaction history',
    please_sign_in_admin: 'Please sign in to access the admin panel',
    loading_admin_panel: 'Loading admin panel...',
    access_denied: 'Access Denied',
    no_admin_privileges: 'You do not have administrator privileges to access this page.',
    access_denied_desc: 'You do not have administrator privileges',
    
    // User Management
    user_management: 'User Management',
    joined: 'Joined',
    remove_admin: 'Remove Admin',
    make_admin: 'Make Admin',
    
    // Class Management
    class_management: 'Class Management',
    add_class: 'Add Class',
    edit_class: 'Edit Class',
    add_new_class: 'Add New Class',
    display_name: 'Display Name',
    internal_name: 'Internal Name',
    delete_confirm_class: 'Are you sure you want to delete this class? This will affect all associated exams.',
    created: 'Created',
    
    // Subscription Plan Management
    subscription_plan_management: 'Subscription Plan Management',
    add_plan: 'Add Plan',
    edit_subscription_plan: 'Edit Subscription Plan',
    add_new_subscription_plan: 'Add New Subscription Plan',
    plan_name: 'Plan Name',
    duration_days: 'Duration (days)',
    max_downloads: 'Max Downloads',
    max_downloads_hint: '999999 for unlimited',
    features_placeholder: 'Access to French curriculum exams\nView corrections and solutions\nDownload exam papers',
    deactivate: 'Deactivate',
    activate: 'Activate',
    unlimited: 'Unlimited',
    delete_confirm_plan: 'Are you sure you want to delete this subscription plan? This will affect all associated subscriptions.',
    
    // Active Subscriptions
    active_subscriptions: 'Active Subscriptions',
    started: 'Started',
    expires: 'Expires',
    auto_renew: 'Auto Renew',
    days_left: 'days left',
    cancel_subscription: 'Cancel',
    cancel_confirm_subscription: 'Are you sure you want to cancel this subscription?',
    
    // Transaction History
    transaction_history: 'Transaction History',
    date: 'Date',
    amount: 'Amount',
    provider: 'Provider',
    reference: 'Reference',
  },
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [language, setLanguage] = useState<'fr' | 'en'>('fr');

  useEffect(() => {
    const storedLang = localStorage.getItem('language') as 'fr' | 'en' | null;
    if (storedLang) {
      setLanguage(storedLang);
    }
  }, []);

  const handleSetLanguage = (lang: 'fr' | 'en') => {
    setLanguage(lang);
    localStorage.setItem('language', lang);
  };

  const t = (key: string): string => {
    return translations[language][key as keyof typeof translations['fr']] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage: handleSetLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}
