// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';
import { brokeredPreviewStorage } from './previewAuthStorage';

const SUPABASE_URL = "https://nrcdtxgmlhxbtfppxqop.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5yY2R0eGdtbGh4YnRmcHB4cW9wIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc0OTIxOTYsImV4cCI6MjA3MzA2ODE5Nn0.gQP0cZoQGVPhppmZTCaUdmm1C7yB6MiyI7izmnHl_2I";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: brokeredPreviewStorage(),
    persistSession: true,
    autoRefreshToken: true,
  }
});